// Generated by scripts/generate-browser-deferred-app-runtime.mjs. Do not edit.
/** @internal Canonical compiler-owned client-module path. */
export const kovoDeferredAppRuntimeModulePath: string = '/c/kovo-generated-app-runtime.client.js';
/** @internal Immutable href derived from the exact generated representation. */
export const kovoDeferredAppRuntimeModuleHref: string =
  '/c/__v/75c2a77195d071807e65016b76c8bd859f2286522c6bdd1443d999b4a66aa921/kovo-generated-app-runtime.client.js';
