// Generated by scripts/generate-browser-deferred-app-runtime.mjs. Do not edit.
/** @internal Canonical compiler-owned client-module path. */
export const kovoDeferredAppRuntimeModulePath: string = '/c/kovo-generated-app-runtime.client.js';
/** @internal Immutable href derived from the exact generated representation. */
export const kovoDeferredAppRuntimeModuleHref: string =
  '/c/__v/88c193ae7e37ce45cc19024b33b27a65a8438c319d5163a3311074de44aac8ee/kovo-generated-app-runtime.client.js';
