// Generated by scripts/generate-browser-deferred-app-runtime.mjs. Do not edit.
/** @internal Canonical compiler-owned client-module path. */
export const kovoDeferredAppRuntimeModulePath: string = '/c/kovo-generated-app-runtime.client.js';
/** @internal Immutable href derived from the exact generated representation. */
export const kovoDeferredAppRuntimeModuleHref: string =
  '/c/__v/81a74bb8c52e50aefe7617397bcbba037bc0ab1434bc6357394e9c8840d1da51/kovo-generated-app-runtime.client.js';
