// Generated by the API-tier split; keep package public subpaths curated.
export {
  accordionContentAttributes,
  accordionHeaderAttributes,
  accordionItemAttributes,
  accordionItemOpen,
  accordionRootAttributes,
  accordionTriggerAttributes,
} from '../primitives/accordion.js';
export type {
  AccordionChangeDetail,
  AccordionChangeOptions,
  AccordionChangeReason,
  AccordionChangeResult,
  AccordionContentAttributeOptions,
  AccordionHeaderAttributeOptions,
  AccordionItem,
  AccordionItemOptions,
  AccordionKeyboardEvent,
  AccordionMoveResult,
  AccordionPrimitiveAttributes,
  AccordionState,
  AccordionTriggerAttributeOptions,
  AccordionTriggerEvent,
  AccordionType,
  AccordionValue,
} from '../primitives/accordion.js';
