// Generated from packages/ui/scripts/primitive-component-manifest.mjs. Run `node packages/ui/scripts/build-registry.mjs --write`.
// Public facade for @kovojs/headless-ui/autocomplete; implementation-only helpers stay in src/primitives.
export {
  autocompleteOptionSelected,
  autocompleteOptionHighlighted,
  autocompleteValueText,
  autocompleteSuggestions,
  autocompleteRootAttributes,
  autocompleteInputAttributes,
  autocompleteListAttributes,
  autocompleteOptionAttributes,
  autocompleteValueAttributes,
} from '../primitives/autocomplete.js';
export type {
  AutocompleteItem,
  AutocompleteState,
  AutocompleteRootAttributeOptions,
  AutocompleteInputAttributeOptions,
  AutocompleteListAttributeOptions,
  AutocompleteOptionAttributeOptions,
  AutocompleteValueAttributeOptions,
  AutocompleteInputChangeReason,
  AutocompleteValueChangeReason,
  AutocompleteOpenChangeReason,
  AutocompleteInputChangeDetail,
  AutocompleteValueChangeDetail,
  AutocompleteOpenChangeDetail,
  AutocompleteChangeOptions,
  AutocompleteInputChangeResult,
  AutocompleteValueChangeResult,
  AutocompleteOpenChangeResult,
  AutocompleteMoveResult,
  AutocompleteOptionSelectResult,
  AutocompleteTypeaheadOptions,
  AutocompleteTypeaheadResult,
  AutocompletePrimitiveAttributes,
  AutocompleteInputEvent,
  AutocompleteOptionEvent,
  AutocompleteKeyboardEvent,
  AutocompleteKeyboardResult,
} from '../primitives/autocomplete.js';
