// Generated by the API-tier split; keep package public subpaths curated.
export {
  avatarFallbackAttributes,
  avatarImageAttributes,
  avatarImageState,
  avatarRootAttributes,
} from '../primitives/avatar.js';
export type {
  AvatarComputedState,
  AvatarFallbackAttributeOptions,
  AvatarImageAttributeOptions,
  AvatarImageEvent,
  AvatarImageStatus,
  AvatarImageStatusResult,
  AvatarPrimitiveAttributes,
  AvatarRootAttributeOptions,
  AvatarState,
} from '../primitives/avatar.js';
