// Generated by the API-tier split; keep package public subpaths curated.
export { applyCheckboxIndeterminate, checkboxRootAttributes } from '../primitives/checkbox.js';
export type {
  CheckboxChangeDetail,
  CheckboxChangeOptions,
  CheckboxChangeReason,
  CheckboxChangeResult,
  CheckboxCheckedState,
  CheckboxNativeInput,
  CheckboxPrimitiveAttributes,
  CheckboxState,
  CheckboxTriggerEvent,
} from '../primitives/checkbox.js';
