// Generated by the API-tier split; keep package public subpaths curated.
export {
  collapsibleContentAttributes,
  collapsibleRootAttributes,
  collapsibleTriggerAttributes,
} from '../primitives/collapsible.js';
export type {
  CollapsibleAttributeOptions,
  CollapsibleChangeDetail,
  CollapsibleChangeOptions,
  CollapsibleChangeReason,
  CollapsibleChangeResult,
  CollapsiblePrimitiveAttributes,
  CollapsibleState,
  CollapsibleTriggerEvent,
} from '../primitives/collapsible.js';
