// Generated from packages/ui/scripts/primitive-component-manifest.mjs. Run `node packages/ui/scripts/build-registry.mjs --write`.
// Public facade for @kovojs/headless-ui/combobox; implementation-only helpers stay in src/primitives.
export {
  comboboxOptionSelected,
  comboboxOptionHighlighted,
  comboboxValueText,
  comboboxFilteredItems,
  comboboxRootAttributes,
  comboboxInputAttributes,
  comboboxListboxAttributes,
  comboboxOptionAttributes,
  comboboxValueAttributes,
} from '../primitives/combobox.js';
export type {
  ComboboxItem,
  ComboboxState,
  ComboboxRootAttributeOptions,
  ComboboxInputAttributeOptions,
  ComboboxListboxAttributeOptions,
  ComboboxOptionAttributeOptions,
  ComboboxValueAttributeOptions,
  ComboboxValueChangeReason,
  ComboboxOpenChangeReason,
  ComboboxValueChangeDetail,
  ComboboxOpenChangeDetail,
  ComboboxChangeOptions,
  ComboboxValueChangeResult,
  ComboboxOpenChangeResult,
  ComboboxMoveResult,
  ComboboxOptionSelectResult,
  ComboboxTypeaheadOptions,
  ComboboxTypeaheadResult,
  ComboboxPrimitiveAttributes,
  ComboboxInputEvent,
  ComboboxOptionEvent,
  ComboboxKeyboardEvent,
  ComboboxKeyboardResult,
} from '../primitives/combobox.js';
