// Generated from packages/ui/scripts/primitive-component-manifest.mjs. Run `node packages/ui/scripts/build-registry.mjs --write`.
// Public facade for @kovojs/headless-ui/command; implementation-only helpers stay in src/primitives.
export {
  commandRootAttributes,
  commandTriggerAttributes,
  commandDialogAttributes,
  commandCloseAttributes,
  commandInputAttributes,
  commandListboxAttributes,
  commandItemAttributes,
  commandEmptyAttributes,
  commandItemHighlighted,
  commandItemSelected,
  commandValueText,
  commandFilteredItems,
} from '../primitives/command.js';
export type {
  CommandItem,
  CommandState,
  CommandRootAttributeOptions,
  CommandTriggerAttributeOptions,
  CommandDialogAttributeOptions,
  CommandCloseAttributeOptions,
  CommandInputAttributeOptions,
  CommandListboxAttributeOptions,
  CommandItemAttributeOptions,
  CommandEmptyAttributeOptions,
  CommandOpenChangeReason,
  CommandInputChangeReason,
  CommandValueChangeReason,
  CommandOpenChangeDetail,
  CommandInputChangeDetail,
  CommandValueChangeDetail,
  CommandChangeOptions,
  CommandOpenChangeResult,
  CommandInputChangeResult,
  CommandValueChangeResult,
  CommandSelectResult,
  CommandMoveResult,
  CommandKeyboardResult,
  CommandPrimitiveAttributes,
  CommandTriggerEvent,
  CommandCloseEvent,
  CommandCancelEvent,
  CommandItemEvent,
  CommandInputEvent,
  CommandKeyboardEvent,
  CommandBeforeToggleEvent,
} from '../primitives/command.js';
