// Generated from packages/ui/scripts/primitive-component-manifest.mjs. Run `node packages/ui/scripts/build-registry.mjs --write`.
// Public facade for @kovojs/headless-ui/context-menu; implementation-only helpers stay in src/primitives.
export {
  contextMenuRootAttributes,
  contextMenuTriggerAttributes,
  contextMenuContentAttributes,
  contextMenuItemAttributes,
  contextMenuGroupAttributes,
  contextMenuSeparatorAttributes,
  contextMenuItemHighlighted,
  contextMenuPointFromEvent,
  contextMenuFocusElement,
} from '../primitives/context-menu.js';
export type {
  ContextMenuPoint,
  ContextMenuItem,
  ContextMenuState,
  ContextMenuRootAttributeOptions,
  ContextMenuTriggerAttributeOptions,
  ContextMenuContentAttributeOptions,
  ContextMenuItemAttributeOptions,
  ContextMenuGroupAttributeOptions,
  ContextMenuSeparatorAttributeOptions,
  ContextMenuOpenChangeReason,
  ContextMenuSelectReason,
  ContextMenuOpenChangeDetail,
  ContextMenuSelectDetail,
  ContextMenuChangeOptions,
  ContextMenuOpenChangeResult,
  ContextMenuSelectResult,
  ContextMenuMoveResult,
  ContextMenuTypeaheadOptions,
  ContextMenuTypeaheadResult,
  ContextMenuPrimitiveAttributes,
  ContextMenuTriggerEvent,
  ContextMenuItemEvent,
  ContextMenuKeyboardEvent,
  ContextMenuFocusEvent,
  ContextMenuFocusOptions,
} from '../primitives/context-menu.js';
