// Generated by the API-tier split; keep package public subpaths curated.
export {
  dialogCloseAttributes,
  dialogContentAttributes,
  dialogRootAttributes,
  dialogTriggerAttributes,
} from '../primitives/dialog.js';
export type {
  DialogAttributeOptions,
  DialogBeforeToggleEvent,
  DialogCancelEvent,
  DialogChangeDetail,
  DialogChangeOptions,
  DialogChangeReason,
  DialogChangeResult,
  DialogCloseEvent,
  DialogPrimitiveAttributes,
  DialogState,
  DialogTriggerEvent,
} from '../primitives/dialog.js';
