// Generated by the API-tier split; keep package public subpaths curated.
export {
  disclosureContentAttributes,
  disclosureRootAttributes,
  disclosureTriggerAttributes,
} from '../primitives/disclosure.js';
export type {
  DisclosureAttributeOptions,
  DisclosureChangeDetail,
  DisclosureChangeOptions,
  DisclosureChangeReason,
  DisclosureChangeResult,
  DisclosurePrimitiveAttributes,
  DisclosureState,
  DisclosureTriggerEvent,
} from '../primitives/disclosure.js';
