// Generated from packages/ui/scripts/primitive-component-manifest.mjs. Run `node packages/ui/scripts/build-registry.mjs --write`.
// Public facade for @kovojs/headless-ui/dropdown-menu; implementation-only helpers stay in src/primitives.
export {
  dropdownMenuRootAttributes,
  dropdownMenuTriggerAttributes,
  dropdownMenuContentAttributes,
  dropdownMenuItemAttributes,
  dropdownMenuGroupAttributes,
  dropdownMenuSeparatorAttributes,
  dropdownMenuItemHighlighted,
  dropdownMenuFocusElement,
} from '../primitives/dropdown-menu.js';
export type {
  DropdownMenuItem,
  DropdownMenuState,
  DropdownMenuRootAttributeOptions,
  DropdownMenuTriggerAttributeOptions,
  DropdownMenuContentAttributeOptions,
  DropdownMenuItemAttributeOptions,
  DropdownMenuGroupAttributeOptions,
  DropdownMenuSeparatorAttributeOptions,
  DropdownMenuOpenChangeReason,
  DropdownMenuSelectReason,
  DropdownMenuOpenChangeDetail,
  DropdownMenuSelectDetail,
  DropdownMenuChangeOptions,
  DropdownMenuOpenChangeResult,
  DropdownMenuSelectResult,
  DropdownMenuMoveResult,
  DropdownMenuTypeaheadOptions,
  DropdownMenuTypeaheadResult,
  DropdownMenuPrimitiveAttributes,
  DropdownMenuTriggerEvent,
  DropdownMenuItemEvent,
  DropdownMenuKeyboardEvent,
  DropdownMenuFocusEvent,
  DropdownMenuFocusOptions,
} from '../primitives/dropdown-menu.js';
