// Generated from packages/ui/scripts/primitive-component-manifest.mjs. Run `node packages/ui/scripts/build-registry.mjs --write`.
// Public facade for @kovojs/headless-ui/menubar; implementation-only helpers stay in src/primitives.
export {
  menubarRootAttributes,
  menubarItemAttributes,
  menubarSubmenuAttributes,
  menubarGroupAttributes,
  menubarSeparatorAttributes,
  menubarItemHighlighted,
  menubarItemOpen,
  menubarFocusElement,
} from '../primitives/menubar.js';
export type {
  MenubarItem,
  MenubarState,
  MenubarRootAttributeOptions,
  MenubarItemAttributeOptions,
  MenubarSubmenuAttributeOptions,
  MenubarGroupAttributeOptions,
  MenubarSeparatorAttributeOptions,
  MenubarOpenChangeReason,
  MenubarSelectReason,
  MenubarOpenChangeDetail,
  MenubarSelectDetail,
  MenubarChangeOptions,
  MenubarOpenChangeResult,
  MenubarSelectResult,
  MenubarMoveOptions,
  MenubarMoveResult,
  MenubarTypeaheadOptions,
  MenubarTypeaheadResult,
  MenubarPrimitiveAttributes,
  MenubarItemEvent,
  MenubarKeyboardEvent,
  MenubarFocusEvent,
  MenubarFocusOptions,
} from '../primitives/menubar.js';
