// Generated from packages/ui/scripts/primitive-component-manifest.mjs. Run `node packages/ui/scripts/build-registry.mjs --write`.
// Public facade for @kovojs/headless-ui/navigation-menu; implementation-only helpers stay in src/primitives.
export {
  navigationMenuRootAttributes,
  navigationMenuListAttributes,
  navigationMenuItemAttributes,
  navigationMenuTriggerAttributes,
  navigationMenuContentAttributes,
  navigationMenuLinkAttributes,
  navigationMenuViewportAttributes,
  navigationMenuIndicatorAttributes,
  navigationMenuItemHighlighted,
  navigationMenuItemOpen,
  navigationMenuFocusElement,
} from '../primitives/navigation-menu.js';
export type {
  NavigationMenuItem,
  NavigationMenuState,
  NavigationMenuRootAttributeOptions,
  NavigationMenuListAttributeOptions,
  NavigationMenuItemAttributeOptions,
  NavigationMenuTriggerAttributeOptions,
  NavigationMenuContentAttributeOptions,
  NavigationMenuLinkAttributeOptions,
  NavigationMenuViewportAttributeOptions,
  NavigationMenuIndicatorAttributeOptions,
  NavigationMenuOpenChangeReason,
  NavigationMenuSelectReason,
  NavigationMenuOpenChangeDetail,
  NavigationMenuSelectDetail,
  NavigationMenuChangeOptions,
  NavigationMenuOpenChangeResult,
  NavigationMenuSelectResult,
  NavigationMenuMoveOptions,
  NavigationMenuMoveResult,
  NavigationMenuTypeaheadOptions,
  NavigationMenuTypeaheadResult,
  NavigationMenuPrimitiveAttributes,
  NavigationMenuTriggerEvent,
  NavigationMenuLinkEvent,
  NavigationMenuKeyboardEvent,
  NavigationMenuFocusEvent,
  NavigationMenuFocusOptions,
} from '../primitives/navigation-menu.js';
