// Generated by the API-tier split; keep package public subpaths curated.
export {
  otpFieldComplete,
  otpFieldHiddenInputAttributes,
  otpFieldInputAttributes,
  otpFieldRootAttributes,
  otpFieldSlotValue,
  otpFieldValueFromString,
} from '../primitives/otp-field.js';
export type {
  OtpFieldChangeDetail,
  OtpFieldChangeOptions,
  OtpFieldChangeReason,
  OtpFieldChangeResult,
  OtpFieldHiddenInputAttributeOptions,
  OtpFieldInputAttributeOptions,
  OtpFieldInputEvent,
  OtpFieldInputMode,
  OtpFieldInputTarget,
  OtpFieldKeyboardEvent,
  OtpFieldMoveResult,
  OtpFieldPasteEvent,
  OtpFieldPrimitiveAttributes,
  OtpFieldRestorableTarget,
  OtpFieldRootAttributeOptions,
  OtpFieldState,
} from '../primitives/otp-field.js';
