// Generated by the API-tier split; keep package public subpaths curated.
export {
  popoverContentAttributes,
  popoverRootAttributes,
  popoverTriggerAttributes,
} from '../primitives/popover.js';
export type {
  PopoverAttributeOptions,
  PopoverBeforeToggleEvent,
  PopoverChangeDetail,
  PopoverChangeOptions,
  PopoverChangeReason,
  PopoverChangeResult,
  PopoverEscapeEvent,
  PopoverPrimitiveAttributes,
  PopoverState,
  PopoverTriggerEvent,
} from '../primitives/popover.js';
