// Generated from packages/ui/scripts/primitive-component-manifest.mjs. Run `node packages/ui/scripts/build-registry.mjs --write`.
// Public facade for @kovojs/headless-ui/scroll-area; implementation-only helpers stay in src/primitives.
export {
  scrollAreaRootAttributes,
  scrollAreaViewportAttributes,
  scrollAreaScrollbarAttributes,
  scrollAreaThumbAttributes,
  scrollAreaCornerAttributes,
  scrollAreaScrollbarState,
  scrollAreaCornerState,
  scrollAreaViewportState,
  scrollAreaThumbGeometry,
} from '../primitives/scroll-area.js';
export type {
  ScrollAreaOrientation,
  ScrollAreaScrollPosition,
  ScrollAreaScrollbars,
  ScrollAreaVisibilityState,
  ScrollAreaState,
  ScrollAreaRootAttributeOptions,
  ScrollAreaViewportAttributeOptions,
  ScrollAreaScrollbarAttributeOptions,
  ScrollAreaThumbAttributeOptions,
  ScrollAreaCornerAttributeOptions,
  ScrollAreaPrimitiveAttributes,
  ScrollAreaViewportTarget,
  ScrollAreaPointerTarget,
  ScrollAreaThumbGeometryOptions,
  ScrollAreaViewportComputedState,
  ScrollAreaViewportScrollResult,
  ScrollAreaThumbGeometry,
  ScrollAreaThumbDragStart,
  ScrollAreaThumbDragOptions,
  ScrollAreaScrollToTrigger,
  ScrollAreaScrollToViewport,
  ScrollAreaScrollToResult,
} from '../primitives/scroll-area.js';
