// Generated from packages/ui/scripts/primitive-component-manifest.mjs. Run `node packages/ui/scripts/build-registry.mjs --write`.
// Public facade for @kovojs/headless-ui/select; implementation-only helpers stay in src/primitives.
export {
  selectItemSelected,
  selectValueText,
  selectRootAttributes,
  selectTriggerAttributes,
  selectHiddenInputAttributes,
  selectContentAttributes,
  selectItemAttributes,
  selectValueAttributes,
} from '../primitives/select.js';
export type {
  SelectItem,
  SelectState,
  SelectRootAttributeOptions,
  SelectTriggerAttributeOptions,
  SelectHiddenInputAttributeOptions,
  SelectContentAttributeOptions,
  SelectItemAttributeOptions,
  SelectValueAttributeOptions,
  SelectChangeReason,
  SelectOpenChangeReason,
  SelectChangeDetail,
  SelectOpenChangeDetail,
  SelectChangeOptions,
  SelectKeyDownOptions,
  SelectChangeResult,
  SelectOpenChangeResult,
  SelectMoveResult,
  SelectOptionSelectResult,
  SelectTypeaheadOptions,
  SelectTypeaheadResult,
  SelectPrimitiveAttributes,
  SelectTriggerEvent,
  SelectKeyboardEvent,
  SelectItemEvent,
  SelectKeyboardResult,
} from '../primitives/select.js';
