// Generated by the API-tier split; keep package public subpaths curated.
export { separatorRootAttributes } from '../primitives/separator.js';
export type {
  SeparatorAttributeOptions,
  SeparatorOrientation,
  SeparatorPrimitiveAttributes,
} from '../primitives/separator.js';
