// Generated by the API-tier split; keep package public subpaths curated.
export { switchRootAttributes } from '../primitives/switch.js';
export type {
  SwitchChangeDetail,
  SwitchChangeOptions,
  SwitchChangeReason,
  SwitchChangeResult,
  SwitchPrimitiveAttributes,
  SwitchState,
  SwitchTriggerEvent,
} from '../primitives/switch.js';
