// Generated by the API-tier split; keep package public subpaths curated.
export {
  tabsItemSelected,
  tabsListAttributes,
  tabsPanelAttributes,
  tabsRootAttributes,
  tabsTriggerAttributes,
} from '../primitives/tabs.js';
export type {
  TabsActivationMode,
  TabsChangeDetail,
  TabsChangeOptions,
  TabsChangeReason,
  TabsChangeResult,
  TabsItem,
  TabsKeyboardEvent,
  TabsKeyboardResult,
  TabsListAttributeOptions,
  TabsMoveResult,
  TabsPanelAttributeOptions,
  TabsPrimitiveAttributes,
  TabsRootAttributeOptions,
  TabsState,
  TabsTriggerAttributeOptions,
  TabsTriggerEvent,
} from '../primitives/tabs.js';
