// Generated from packages/ui/scripts/primitive-component-manifest.mjs. Run `node packages/ui/scripts/build-registry.mjs --write`.
// Public facade for @kovojs/headless-ui/toast; implementation-only helpers stay in src/primitives.
export {
  toastShowEventName,
  toastDismissEventName,
  toastShowEvent,
  toastDismissEvent,
  toastEvents,
  toastShowPayload,
  toastDismissPayload,
  toastViewportAttributes,
  toastRootAttributes,
  toastTitleAttributes,
  toastDescriptionAttributes,
  toastActionAttributes,
  toastCloseAttributes,
  normalizeToastDuration,
} from '../primitives/toast.js';
export type {
  ToastPlacement,
  ToastPoliteness,
  ToastVariant,
  ToastChangeReason,
  ToastShowPayload,
  ToastDismissPayload,
  ToastEventDefinition,
  ToastShowEventDefinition,
  ToastDismissEventDefinition,
  ToastState,
  ToastViewportAttributeOptions,
  ToastRootAttributeOptions,
  ToastPartAttributeOptions,
  ToastActionAttributeOptions,
  ToastChangeValue,
  ToastPrimitiveAttributes,
} from '../primitives/toast.js';
