// Generated by the API-tier split; keep package public subpaths curated.
export { toggleRootAttributes } from '../primitives/toggle.js';
export type {
  ToggleChangeDetail,
  ToggleChangeOptions,
  ToggleChangeReason,
  ToggleChangeResult,
  TogglePrimitiveAttributes,
  ToggleState,
  ToggleTriggerEvent,
} from '../primitives/toggle.js';
