// Generated by the API-tier split; keep package public subpaths curated.
export {
  tooltipContentAttributes,
  tooltipRootAttributes,
  tooltipTriggerAttributes,
} from '../primitives/tooltip.js';
export type {
  TooltipAttributeOptions,
  TooltipChangeDetail,
  TooltipChangeOptions,
  TooltipChangeReason,
  TooltipChangeResult,
  TooltipEscapeEvent,
  TooltipPrimitiveAttributes,
  TooltipState,
  TooltipTriggerEvent,
} from '../primitives/tooltip.js';
