// Emit the committed `src/generated/kovo-ui.css` stylesheet for the CRM example:
// the shared @kovojs/ui design-token sheet plus the StyleX CSS for the
// @kovojs/ui components the app imports. `src/styles.css` @imports this file, so
// the single `/assets/styles.css` the app already links carries the component
// styling (SPEC §6.1.1, §13.1). Re-run after upgrading @kovojs/ui.
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { registerHooks } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// Resolve the workspace `.ts` sources behind `.js` specifiers (matches emit-graph).
registerHooks({
  resolve(specifier, context, nextResolve) {
    if (specifier.startsWith('.') && specifier.endsWith('.js') && context.parentURL) {
      const tsUrl = new URL(specifier.replace(/\.js$/, '.ts'), context.parentURL);
      if (existsSync(tsUrl)) return nextResolve(tsUrl.href, context);
    }
    return nextResolve(specifier, context);
  },
});

const { extractPackageComponentCss } = await import('@kovojs/compiler/package-styles');
const { kovoUiTokenSheetCss } = await import('@kovojs/headless-ui');

const scriptDir = dirname(fileURLToPath(import.meta.url));
const crmRoot = resolve(scriptDir, '..');
const outPath = resolve(crmRoot, 'src/generated/kovo-ui.css');

const result = extractPackageComponentCss('@kovojs/ui', {
  fileName: resolve(crmRoot, 'src/app-shell.ts'),
  source: "import { Button } from '@kovojs/ui/button';",
  packagePrefixDiscoveryRoot: crmRoot,
});

if (!result.css) {
  throw new Error('emit-ui-css: no @kovojs/ui component CSS was extracted.');
}
for (const diagnostic of result.diagnostics) {
  // Coverage gap (e.g. keyframes-by-identifier): the named component would render
  // unstyled. Warn loudly so the example never silently ships one.
  console.warn(`emit-ui-css: ${diagnostic.fileName}: ${diagnostic.message}`);
}

const banner =
  '/* GENERATED by scripts/emit-ui-css.mjs — do not edit.\n' +
  '   @kovojs/ui design tokens + component StyleX CSS (SPEC §6.1.1, §13.1). */\n';
// Drop the Tailwind-only `@theme inline { ... }` alias block: it is not a real
// CSS rule outside Tailwind, so its `--color-*` aliases would not resolve and a
// strict parser warns. The real `:root` / `[data-theme="dark"]` token blocks
// (with `--kovo-color-*` custom properties) are kept for page-chrome theming.
const tokenCss = kovoUiTokenSheetCss.replace(/@theme[^{]*\{[\s\S]*?\n\}/, '').trimStart();
const css = `${banner}\n${tokenCss}\n${result.css}\n`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, css);
console.log(
  `emit-ui-css: wrote ${outPath} (${result.sourceFiles.length} component files scanned).`,
);
