// Emit the committed `src/generated/kovo-ui.css` stylesheet for the commerce
// example: the shared @kovojs/ui design-token sheet plus the StyleX CSS for the
// @kovojs/ui components the app imports. `src/styles.css` @imports this file, so
// the single `/assets/styles.css` the app already links carries the component
// styling (SPEC §6.1.1, §13.1). Re-run after upgrading @kovojs/ui.
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { registerHooks } from 'node:module';
import { tmpdir } from 'node:os';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// Resolve the workspace `.ts` sources behind `.js` specifiers (matches emit-graph).
registerHooks({
  resolve(specifier, context, nextResolve) {
    if (specifier.startsWith('.') && specifier.endsWith('.js') && context.parentURL) {
      const tsUrl = new URL(specifier.replace(/\.js$/, '.ts'), context.parentURL);
      if (existsSync(tsUrl)) return nextResolve(tsUrl.href, context);
    }
    return nextResolve(specifier, context);
  },
});

const { kovoUiTokenSheetCss } = await import('@kovojs/headless-ui');

const scriptDir = dirname(fileURLToPath(import.meta.url));
const commerceRoot = resolve(scriptDir, '..');
const outPath = resolve(commerceRoot, 'src/generated/kovo-ui.css');
const tempRoot = mkdtempSync(resolve(tmpdir(), 'kovo-commerce-ui-css-'));
const componentCssPath = resolve(tempRoot, 'kovo-ui-components.css');

try {
  const output = execFileSync(
    'kovo',
    [
      'compile',
      'package-css',
      '@kovojs/ui',
      '--entry',
      resolve(commerceRoot, 'src/app.tsx'),
      '--out',
      componentCssPath,
    ],
    { cwd: commerceRoot, encoding: 'utf8' },
  );
  const warnedFiles = [...output.matchAll(/^WARN package-css file=("[^"]+")/gm)].map((match) =>
    JSON.parse(match[1]),
  );
  for (const fileName of warnedFiles) {
    // Coverage gap (e.g. keyframes-by-identifier): the named component would render
    // unstyled. Warn loudly so the example never silently ships one.
    console.warn(`emit-ui-css: ${fileName}: package component CSS extraction warning`);
  }

  const banner =
    '/* GENERATED by scripts/emit-ui-css.mjs — do not edit.\n' +
    '   @kovojs/ui design tokens + component StyleX CSS (SPEC §6.1.1, §13.1). */\n';
  // Drop the Tailwind-only `@theme inline { ... }` alias block: it is not a real
  // CSS rule outside Tailwind, so its `--color-*` aliases would not resolve and a
  // strict parser warns. The real `:root` / `[data-theme="dark"]` token blocks
  // (with `--kovo-color-*` custom properties) are kept for page-chrome theming.
  const tokenCss = kovoUiTokenSheetCss.replace(/@theme[^{]*\{[\s\S]*?\n\}/, '').trimStart();
  const componentCss = readFileSync(componentCssPath, 'utf8');
  const css = `${banner}\n${tokenCss}\n${componentCss}\n`;

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, css);
  console.log(`emit-ui-css: wrote ${outPath}.`);
} finally {
  rmSync(tempRoot, { force: true, recursive: true });
}
