#!/usr/bin/env node
import { randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { basename, dirname, isAbsolute, relative, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

export interface CreateKovoOptions {
  dialect?: CreateKovoDialect;
  name: string;
}

export type CreateKovoDialect = 'postgres' | 'sqlite';

export interface GeneratedFile {
  path: string;
  source: string;
}

export interface CreateKovoProject {
  files: GeneratedFile[];
  name: string;
}

export interface WriteKovoProjectResult {
  files: string[];
  name: string;
  root: string;
}

/** Usage line emitted by the `create-kovo` bin and consumed by the docs generator. */
export const CREATE_KOVO_USAGE =
  'usage: create-kovo <target-directory> [--name <package-name>] [--dialect postgres|sqlite]';

const templateRoot = new URL('../templates/', import.meta.url);
interface TemplateFile {
  path: string;
  sqlitePath?: string;
}

const templateFiles: readonly TemplateFile[] = [
  { path: 'package.json', sqlitePath: 'package.sqlite.json' },
  'kovo.config.ts',
  'vite.config.ts',
  '.github/workflows/ci.yml',
  { path: 'README.md', sqlitePath: 'README.sqlite.md' },
  { path: 'src/schema.ts', sqlitePath: 'src/schema.sqlite.ts' },
  { path: 'src/db.ts', sqlitePath: 'src/db.sqlite.ts' },
  { path: 'src/auth.ts', sqlitePath: 'src/auth.sqlite.ts' },
  'src/queries.ts',
  'src/mutations.ts',
  'src/components/contacts.tsx',
  'src/components/auth-forms.tsx',
  'src/app.tsx',
  'src/app.test.ts',
  'src/theme.ts',
  'src/styles.css',
].map((file) => (typeof file === 'string' ? { path: file } : file));

// SECURITY (SECURITY_FINDINGS.md M5): every scaffolded app must start with its own
// strong, secret CSRF HMAC key — never a known constant from the template. We generate
// a per-project random secret at scaffold time and write it into `.env` (gitignored),
// while `src/auth.ts` reads `process.env.KOVO_CSRF_SECRET` and fails closed if it is
// missing or still the placeholder.
export const csrfSecretEnvVar = 'KOVO_CSRF_SECRET';
const csrfSecretPlaceholder = 'replace-with-a-deployed-secret';

export function generateCsrfSecret(): string {
  return randomBytes(32).toString('base64url');
}

function renderEnvFile(secret: string): string {
  return [
    '# Local development environment for this Kovo app.',
    '# Generated by create-kovo. This file is gitignored; do NOT commit real secrets.',
    '',
    '# CSRF HMAC key. SECURITY: keep this secret and unique per deployment',
    '# (regenerate with `openssl rand -base64 32`). src/auth.ts fails closed if it is',
    `# missing or still the '${csrfSecretPlaceholder}' placeholder.`,
    `${csrfSecretEnvVar}=${secret}`,
    '',
  ].join('\n');
}

function renderEnvExampleFile(): string {
  return [
    '# Copy this file to .env and fill in real secrets before deploying.',
    '# Generate a strong CSRF secret with: openssl rand -base64 32',
    `${csrfSecretEnvVar}=${csrfSecretPlaceholder}`,
    '',
  ].join('\n');
}

const gitignoreEntries = ['node_modules', 'dist', '.env', '.env.*', '!.env.example', ''].join('\n');

export function createKovoProject(options: CreateKovoOptions): CreateKovoProject {
  const packageName = normalizePackageName(options.name);
  const dialect = options.dialect ?? 'postgres';
  const values = { name: packageName };
  const csrfSecret = generateCsrfSecret();

  return {
    files: [
      ...templateFiles.map((file) => ({
        path: file.path,
        source: renderTemplate(readTemplate(templatePathForDialect(file, dialect)), values),
      })),
      // Generated (non-template) project files: a per-project random CSRF secret and the
      // ignore rules that keep the real secret out of version control.
      { path: '.env', source: renderEnvFile(csrfSecret) },
      { path: '.env.example', source: renderEnvExampleFile() },
      { path: '.gitignore', source: gitignoreEntries },
    ],
    name: packageName,
  };
}

export function writeKovoProject(
  targetDirectory: string,
  options: Partial<CreateKovoOptions> = {},
): WriteKovoProjectResult {
  const root = resolve(targetDirectory);
  const name = options.name ?? basename(root);
  const project = createKovoProject({
    ...(options.dialect === undefined ? {} : { dialect: options.dialect }),
    name,
  });

  assertWritableTarget(root);

  for (const file of project.files) {
    const destination = resolve(root, file.path);

    const relativeDestination = relative(root, destination);

    if (
      relativeDestination === '' ||
      relativeDestination.startsWith('..') ||
      isAbsolute(relativeDestination)
    ) {
      throw new Error(`Refusing to write outside target directory: ${file.path}`);
    }

    mkdirSync(dirname(destination), { recursive: true });
    writeFileSync(destination, file.source, 'utf8');
  }

  return {
    files: project.files.map((file) => file.path),
    name: project.name,
    root,
  };
}

export function main(args: readonly string[] = process.argv.slice(2)): number {
  const [targetDirectory, ...rest] = args;

  if (!targetDirectory || targetDirectory === '--help' || targetDirectory === '-h') {
    process.stdout.write(`${CREATE_KOVO_USAGE}\n`);
    return targetDirectory ? 0 : 1;
  }

  try {
    const name = readNameOption(rest);
    const dialect = readDialectOption(rest);
    const result = writeKovoProject(targetDirectory, {
      ...(dialect === undefined ? {} : { dialect }),
      ...(name === undefined ? {} : { name }),
    });
    process.stdout.write(`create-kovo: wrote ${result.files.length} files to ${result.root}\n`);
    return 0;
  } catch (error) {
    process.stderr.write(
      `create-kovo: ${error instanceof Error ? error.message : String(error)}\n`,
    );
    return 1;
  }
}

function readTemplate(path: string): string {
  return readFileSync(new URL(path, templateRoot), 'utf8');
}

function templatePathForDialect(file: TemplateFile, dialect: CreateKovoDialect): string {
  return dialect === 'sqlite' && file.sqlitePath ? file.sqlitePath : file.path;
}

function renderTemplate(source: string, values: Record<string, string>): string {
  return source.replaceAll(/\{\{([a-zA-Z0-9_]+)\}\}/g, (_match, key: string) => {
    const value = values[key];
    if (value === undefined) {
      throw new Error(`Unknown create-kovo template variable: ${key}`);
    }
    return value;
  });
}

function normalizePackageName(name: string): string {
  const normalized = name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-|-$/g, '');

  return normalized || 'kovo-app';
}

function assertWritableTarget(root: string): void {
  if (!existsSync(root)) {
    return;
  }

  const stats = statSync(root);

  if (!stats.isDirectory()) {
    throw new Error(`Target exists and is not a directory: ${root}`);
  }

  const existingEntries = readdirSync(root);

  if (existingEntries.length > 0) {
    throw new Error(`Target directory is not empty: ${root}`);
  }
}

function readNameOption(args: readonly string[]): string | undefined {
  let name: string | undefined;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (!arg) continue;

    if (arg === '--name') {
      name = args[index + 1];
      index += 1;
      continue;
    }

    if (arg.startsWith('--name=')) {
      name = arg.slice('--name='.length);
    }
  }

  return name;
}

function readDialectOption(args: readonly string[]): CreateKovoDialect | undefined {
  let dialect: CreateKovoDialect | undefined;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (!arg) continue;

    if (arg === '--sqlite') {
      dialect = 'sqlite';
      continue;
    }

    if (arg === '--postgres') {
      dialect = 'postgres';
      continue;
    }

    if (arg === '--dialect') {
      dialect = parseDialectOption(args[index + 1]);
      index += 1;
      continue;
    }

    if (arg.startsWith('--dialect=')) {
      dialect = parseDialectOption(arg.slice('--dialect='.length));
    }
  }

  return dialect;
}

function parseDialectOption(value: string | undefined): CreateKovoDialect {
  if (value === 'postgres' || value === 'sqlite') return value;

  throw new Error(`Unsupported create-kovo dialect: ${value ?? '<missing>'}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  process.exitCode = main();
}
