#!/usr/bin/env node
import { execFileSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  readdirSync,
  realpathSync,
  readFileSync,
  statSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { basename, dirname, isAbsolute, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  bundledKovoDocsMirrorFiles,
  bundledKovoRulesSource,
  renderKovoRulesBlock,
} from '@kovojs/core/internal/agent-docs';

export interface CreateKovoOptions {
  dialect?: CreateKovoDialect;
  name: string;
}

export type CreateKovoDialect = 'postgres' | 'sqlite';

export interface GeneratedFile {
  path: string;
  source: string;
  symlinkTarget?: string;
}

export interface CreateKovoProject {
  files: GeneratedFile[];
  name: string;
}

export interface WriteKovoProjectResult {
  files: string[];
  name: string;
  root: string;
}

export interface WriteKovoProjectOptions extends Partial<CreateKovoOptions> {
  disableGit?: boolean;
}

/** Usage line emitted by the `create-kovo` bin and consumed by the docs generator. */
export const CREATE_KOVO_USAGE = 'create-kovo <target-directory> [options]';

export const CREATE_KOVO_HELP = [
  'create-kovo',
  '',
  'Create a new Kovo application.',
  '',
  'Usage',
  `  ${CREATE_KOVO_USAGE}`,
  '',
  'Options',
  '  --name <name>               Package name for package.json.',
  '                              Default: normalized target directory name.',
  '',
  '  --dialect <postgres|sqlite> Database scaffold to generate.',
  '                              Default: postgres.',
  '',
  '  --postgres                  Alias for --dialect postgres.',
  '  --sqlite                    Alias for --dialect sqlite.',
  '  --disable-git               Do not initialize a Git repository.',
  '',
  '  -h, --help                  Show this help.',
  '',
  'Examples',
  '  create-kovo my-app',
  '  create-kovo my-app --name acme-todos',
  '  create-kovo my-app --dialect sqlite',
  '',
  'Defaults',
  '  target-directory            Required.',
  '  name                        basename(target-directory), normalized for npm.',
  '  dialect                     postgres.',
  `  package manager             ${rootPackageManager()}.`,
  '',
].join('\n');

const templateRoot = new URL('../templates/', import.meta.url);
interface TemplateFile {
  path: string;
  sqlitePath?: string;
}

const templateFiles: readonly TemplateFile[] = [
  { path: 'package.json', sqlitePath: 'package.sqlite.json' },
  'tsconfig.json',
  'kovo.config.ts',
  'vite.config.ts',
  '.github/workflows/ci.yml',
  { path: 'README.md', sqlitePath: 'README.sqlite.md' },
  'scripts/check-sound-subset.mjs',
  { path: 'src/schema.ts', sqlitePath: 'src/schema.sqlite.ts' },
  { path: 'src/db.ts', sqlitePath: 'src/db.sqlite.ts' },
  { path: 'src/auth.ts', sqlitePath: 'src/auth.sqlite.ts' },
  'src/queries.ts',
  'src/mutations.ts',
  'src/components/contacts.tsx',
  'src/components/auth-forms.tsx',
  'src/app.tsx',
  'src/app.test.ts',
  'src/endpoint-posture.test.ts',
  'src/theme.ts',
  'src/styles.css',
].map((file) => (typeof file === 'string' ? { path: file } : file));

// SECURITY (SECURITY_FINDINGS.md M5): every scaffolded app must start with its own
// strong, secret CSRF HMAC key — never a known constant from the template. We generate
// a per-project random secret at scaffold time and write it into `.env` (gitignored),
// while `src/auth.ts` reads `process.env.KOVO_CSRF_SECRET` and fails closed if it is
// missing or still the placeholder.
export const csrfSecretEnvVar = 'KOVO_CSRF_SECRET';
export const demoPasswordEnvVar = 'KOVO_DEMO_PASSWORD';
const csrfSecretPlaceholder = 'replace-with-a-deployed-secret';
const demoPasswordPlaceholder = 'replace-with-a-local-demo-password';

export function generateCsrfSecret(): string {
  return randomBytes(32).toString('base64url');
}

export function generateDemoPassword(): string {
  return randomBytes(18).toString('base64url');
}

function renderEnvFile(secret: string, demoPassword: string): string {
  return [
    '# Local development environment for this Kovo app.',
    '# Generated by create-kovo. This file is gitignored; do NOT commit real secrets.',
    '',
    '# CSRF HMAC key. SECURITY: keep this secret and unique per deployment',
    '# (regenerate with `openssl rand -base64 32`). src/auth.ts fails closed if it is',
    `# missing or still the '${csrfSecretPlaceholder}' placeholder.`,
    `${csrfSecretEnvVar}=${secret}`,
    '',
    '# Local seeded demo account password. Development only; do not reuse in production.',
    `${demoPasswordEnvVar}=${demoPassword}`,
    '',
  ].join('\n');
}

function renderEnvExampleFile(): string {
  return [
    '# Copy this file to .env and fill in real secrets before deploying.',
    '# Generate a strong CSRF secret with: openssl rand -base64 32',
    `${csrfSecretEnvVar}=${csrfSecretPlaceholder}`,
    '# Local-only demo seed password. Leave unset in production.',
    `${demoPasswordEnvVar}=${demoPasswordPlaceholder}`,
    '',
  ].join('\n');
}

const gitignoreEntries = [
  'node_modules',
  'dist',
  '.env',
  '.env.*',
  '!.env.example',
  '.kovo/endpoint-posture.json',
  '',
].join('\n');

export function createKovoProject(options: CreateKovoOptions): CreateKovoProject {
  const packageName = normalizePackageName(options.name);
  const dialect = options.dialect ?? 'postgres';
  const values = templateValues(packageName);
  const docsVersion = packageVersion('@kovojs/core');
  const csrfSecret = generateCsrfSecret();
  const demoPassword = generateDemoPassword();
  const kovoRulesBlock = renderKovoRulesBlock({
    rulesSource: bundledKovoRulesSource(),
    version: docsVersion,
  });

  return {
    files: [
      { path: 'AGENTS.md', source: renderAgentsFile(kovoRulesBlock) },
      {
        path: 'CLAUDE.md',
        source: 'See AGENTS.md for agent instructions.\n',
        symlinkTarget: 'AGENTS.md',
      },
      ...bundledKovoDocsMirrorFiles({ version: docsVersion }).map((file) => ({
        path: `.kovo/docs/${file.path}`,
        source: file.source,
      })),
      ...templateFiles.map((file) => ({
        path: file.path,
        source: renderTemplate(readTemplate(templatePathForDialect(file, dialect)), values),
      })),
      // Generated (non-template) project files: a per-project random CSRF secret and the
      // ignore rules that keep the real secret out of version control.
      { path: '.env', source: renderEnvFile(csrfSecret, demoPassword) },
      { path: '.env.example', source: renderEnvExampleFile() },
      { path: '.gitignore', source: gitignoreEntries },
    ],
    name: packageName,
  };
}

export function writeKovoProject(
  targetDirectory: string,
  options: WriteKovoProjectOptions = {},
): WriteKovoProjectResult {
  const root = resolve(targetDirectory);
  const name = options.name ?? basename(root);
  const project = createKovoProject({
    ...(options.dialect === undefined ? {} : { dialect: options.dialect }),
    name,
  });

  assertWritableTarget(root);

  for (const file of project.files) {
    const destination = resolve(root, file.path);

    const relativeDestination = relative(root, destination);

    if (
      relativeDestination === '' ||
      relativeDestination.startsWith('..') ||
      isAbsolute(relativeDestination)
    ) {
      throw new Error(`Refusing to write outside target directory: ${file.path}`);
    }

    mkdirSync(dirname(destination), { recursive: true });
    if (file.symlinkTarget) {
      try {
        symlinkSync(file.symlinkTarget, destination);
        continue;
      } catch {
        writeFileSync(destination, file.source, 'utf8');
        continue;
      }
    }
    writeFileSync(destination, file.source, 'utf8');
  }

  if (!options.disableGit) {
    tryGitInit(root);
  }

  return {
    files: project.files.map((file) => file.path),
    name: project.name,
    root,
  };
}

function renderAgentsFile(kovoRulesBlock: string): string {
  return [
    '# Agent Instructions',
    '',
    'Add project-specific agent instructions here. Keep Kovo framework docs inside the generated block below.',
    '',
    kovoRulesBlock.trimEnd(),
    '',
  ].join('\n');
}

export function main(args: readonly string[] = process.argv.slice(2)): number {
  if (args.includes('--help') || args.includes('-h')) {
    process.stdout.write(CREATE_KOVO_HELP);
    return 0;
  }

  try {
    const options = readCliOptions(args);
    const result = writeKovoProject(options.targetDirectory, {
      ...(options.dialect === undefined ? {} : { dialect: options.dialect }),
      ...(options.name === undefined ? {} : { name: options.name }),
      ...(options.disableGit === undefined ? {} : { disableGit: options.disableGit }),
    });
    process.stdout.write(renderSuccess(result, options.dialect ?? 'postgres'));
    return 0;
  } catch (error) {
    process.stderr.write(renderCliError(error));
    return 1;
  }
}

function readTemplate(path: string): string {
  return readFileSync(new URL(path, templateRoot), 'utf8');
}

function templatePathForDialect(file: TemplateFile, dialect: CreateKovoDialect): string {
  return dialect === 'sqlite' && file.sqlitePath ? file.sqlitePath : file.path;
}

function renderTemplate(source: string, values: Record<string, string>): string {
  return source.replaceAll(/\{\{([a-zA-Z0-9_]+)\}\}/g, (_match, key: string) => {
    const value = values[key];
    if (value === undefined) {
      throw new Error(`Unknown create-kovo template variable: ${key}`);
    }
    return value;
  });
}

function templateValues(name: string): Record<string, string> {
  return {
    kovo_better_auth_version: packageVersion('@kovojs/better-auth'),
    kovo_browser_version: packageVersion('@kovojs/browser'),
    kovo_cli_version: packageVersion('@kovojs/cli'),
    kovo_core_version: packageVersion('@kovojs/core'),
    kovo_drizzle_version: packageVersion('@kovojs/drizzle'),
    kovo_server_version: packageVersion('@kovojs/server'),
    kovo_style_version: packageVersion('@kovojs/style'),
    kovo_ui_version: packageVersion('@kovojs/ui'),
    name,
    package_manager: rootPackageManager(),
  };
}

function packageVersion(packageName: string): string {
  if (!packageName.startsWith('@kovojs/')) {
    throw new Error(`Unsupported create-kovo template package: ${packageName}`);
  }
  const pkg = readOwnPackageJson();
  if (!pkg.version) {
    throw new Error(`Missing package version for ${packageName}`);
  }
  return pkg.version;
}

function rootPackageManager(): string {
  const pkg = readOwnPackageJson();
  const packageManager = pkg.kovo?.starterPackageManager;
  if (!packageManager) {
    throw new Error('create-kovo package.json must declare kovo.starterPackageManager');
  }
  return packageManager;
}

function readOwnPackageJson(): { kovo?: { starterPackageManager?: string }; version?: string } {
  return JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8')) as {
    kovo?: { starterPackageManager?: string };
    version?: string;
  };
}

function normalizePackageName(name: string): string {
  const normalized = name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-|-$/g, '');

  return normalized || 'kovo-app';
}

function assertWritableTarget(root: string): void {
  if (!existsSync(root)) {
    return;
  }

  const stats = statSync(root);

  if (!stats.isDirectory()) {
    throw new Error(`Target exists and is not a directory: ${root}`);
  }

  const existingEntries = readdirSync(root);

  if (existingEntries.length > 0) {
    throw new Error(`Target directory is not empty: ${root}`);
  }
}

function tryGitInit(root: string): boolean {
  if (isInsideVersionControl(root)) {
    return false;
  }

  try {
    execFileSync('git', ['--version'], { stdio: 'ignore' });
  } catch {
    return false;
  }

  try {
    execFileSync('git', ['init', '-b', 'main'], { cwd: root, stdio: 'ignore' });
    return true;
  } catch {
    try {
      execFileSync('git', ['init'], { cwd: root, stdio: 'ignore' });
      return true;
    } catch {
      return false;
    }
  }
}

function isInsideVersionControl(root: string): boolean {
  let current = resolve(root);

  while (true) {
    if (existsSync(resolve(current, '.git')) || existsSync(resolve(current, '.hg'))) {
      return true;
    }

    const parent = dirname(current);
    if (parent === current) return false;
    current = parent;
  }
}

interface CliOptions {
  disableGit?: boolean;
  dialect?: CreateKovoDialect;
  name?: string;
  targetDirectory: string;
}

function readCliOptions(args: readonly string[]): CliOptions {
  let disableGit: boolean | undefined;
  let targetDirectory: string | undefined;
  let name: string | undefined;
  let dialect: CreateKovoDialect | undefined;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (!arg) continue;

    if (arg === '--name') {
      name = readRequiredOptionValue(args, index, '--name');
      index += 1;
      continue;
    }

    if (arg.startsWith('--name=')) {
      name = arg.slice('--name='.length);
      if (!name) throw new Error('Missing value for --name.');
      continue;
    }

    if (arg === '--dialect') {
      dialect = parseDialectOption(readRequiredOptionValue(args, index, '--dialect'));
      index += 1;
      continue;
    }

    if (arg === '--sqlite') {
      dialect = 'sqlite';
      continue;
    }

    if (arg === '--disable-git') {
      disableGit = true;
      continue;
    }

    if (arg === '--postgres') {
      dialect = 'postgres';
      continue;
    }

    if (arg.startsWith('--dialect=')) {
      dialect = parseDialectOption(arg.slice('--dialect='.length));
      continue;
    }

    if (arg.startsWith('-')) {
      throw new Error(`Unknown option: ${arg}`);
    }

    if (targetDirectory) {
      throw new Error(`Unexpected argument: ${arg}`);
    }
    targetDirectory = arg;
  }

  if (!targetDirectory) {
    throw new Error('Missing target directory.');
  }

  return {
    ...(disableGit === undefined ? {} : { disableGit }),
    ...(dialect === undefined ? {} : { dialect }),
    ...(name === undefined ? {} : { name }),
    targetDirectory,
  };
}

function readRequiredOptionValue(args: readonly string[], index: number, option: string): string {
  const value = args[index + 1];
  if (!value || value.startsWith('-')) {
    throw new Error(`Missing value for ${option}.`);
  }
  return value;
}

function parseDialectOption(value: string | undefined): CreateKovoDialect {
  if (value === 'postgres' || value === 'sqlite') return value;

  throw new Error(`Unsupported dialect: ${value ?? '<missing>'}.`);
}

function renderSuccess(result: WriteKovoProjectResult, dialect: CreateKovoDialect): string {
  return [
    'Kovo app created',
    '',
    `  Directory   ${result.root}`,
    `  Name        ${result.name}`,
    `  Dialect     ${dialect}`,
    `  Files       ${result.files.length}`,
    '',
    'Next steps',
    `  cd ${shellQuote(result.root)}`,
    `  ${packageManagerCommand()} install`,
    `  ${packageManagerCommand()} run dev`,
    '',
  ].join('\n');
}

function packageManagerCommand(): string {
  return rootPackageManager().split('@')[0] ?? 'pnpm';
}

function shellQuote(value: string): string {
  if (/^[A-Za-z0-9_/:=.,@%+-]+$/u.test(value)) return value;
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function renderCliError(error: unknown): string {
  const message = error instanceof Error ? error.message : String(error);
  const lines = [`create-kovo: ${message}`];

  if (message === 'Missing target directory.') {
    lines.push(
      '',
      `Usage: ${CREATE_KOVO_USAGE}`,
      '',
      'Run `create-kovo --help` for examples and defaults.',
    );
  } else if (message.startsWith('Target directory is not empty: ')) {
    const root = message.slice('Target directory is not empty: '.length);
    lines.push(
      '',
      `  ${root} already contains files.`,
      '',
      'Choose an empty directory, or remove the existing directory and try again.',
    );
  } else if (message.startsWith('Target exists and is not a directory: ')) {
    const root = message.slice('Target exists and is not a directory: '.length);
    lines.push(
      '',
      `  ${root} is a file, not a directory.`,
      '',
      'Choose a new directory path and try again.',
    );
  } else if (
    message.startsWith('Unsupported dialect: ') ||
    message.startsWith('Unknown option: ') ||
    message.startsWith('Missing value for ') ||
    message.startsWith('Unexpected argument: ')
  ) {
    lines.push('', 'Run `create-kovo --help` to see supported options and defaults.');
  }

  return `${lines.join('\n')}\n`;
}

function isMainModule(): boolean {
  if (!process.argv[1]) return false;

  try {
    return realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url));
  } catch {
    return resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));
  }
}

if (isMainModule()) {
  process.exitCode = main();
}
