// Generated from packages/ui/scripts/primitive-component-manifest.mjs. Run `node packages/ui/scripts/build-registry.mjs --write`.

export const galleryComponentEntries = Object.freeze([
  {
    component: 'accordion',
    demoFunction: 'AccordionDemo',
    path: '/components/accordion',
    summary:
      'Vertically stacked headers that each expand to reveal a panel, with single- or multi-open behavior.',
    title: 'Accordion',
    visualFixture: 'accordion.html.txt',
  },
  {
    component: 'alert',
    demoFunction: 'AlertDemo',
    path: '/components/alert',
    summary: 'A statically rendered status banner that surfaces an important inline message.',
    title: 'Alert',
    visualFixture: 'alert.html.txt',
  },
  {
    component: 'alert-dialog',
    demoFunction: 'AlertDialogDemo',
    path: '/components/alert-dialog',
    summary: 'A modal dialog that interrupts the user to confirm or cancel a consequential action.',
    title: 'Alert Dialog',
    visualFixture: 'alert-dialog.html.txt',
  },
  {
    component: 'autocomplete',
    demoFunction: 'AutocompleteDemo',
    path: '/components/autocomplete',
    summary:
      'A text input that suggests matching options as you type while keeping native typing intact.',
    title: 'Autocomplete',
    visualFixture: 'autocomplete.html.txt',
  },
  {
    component: 'avatar',
    demoFunction: 'AvatarDemo',
    path: '/components/avatar',
    summary:
      'A user image with an automatic fallback to initials or a placeholder when it fails to load.',
    title: 'Avatar',
    visualFixture: 'avatar.html.txt',
  },
  {
    component: 'badge',
    demoFunction: 'BadgeDemo',
    path: '/components/badge',
    summary: 'A small inline count or status label attached to another element.',
    title: 'Badge',
    visualFixture: 'badge.html.txt',
  },
  {
    component: 'breadcrumb',
    demoFunction: 'BreadcrumbDemo',
    path: '/components/breadcrumb',
    summary: "An ordered trail of links showing the current page's position in the hierarchy.",
    title: 'Breadcrumb',
    visualFixture: 'breadcrumb.html.txt',
  },
  {
    component: 'button',
    demoFunction: 'ButtonDemo',
    path: '/components/button',
    summary: 'The base interactive control, with variant, size, and disabled/loading states.',
    title: 'Button',
    visualFixture: 'button.html.txt',
  },
  {
    component: 'card',
    demoFunction: 'CardDemo',
    path: '/components/card',
    summary:
      'A surface container that groups related content with optional header, body, and footer.',
    title: 'Card',
    visualFixture: 'card.html.txt',
  },
  {
    component: 'checkbox',
    demoFunction: 'CheckboxDemo',
    path: '/components/checkbox',
    summary: 'A single toggle for an on/off (or indeterminate) boolean value.',
    title: 'Checkbox',
    visualFixture: 'checkbox.html.txt',
  },
  {
    component: 'checkbox-group',
    demoFunction: 'CheckboxGroupDemo',
    path: '/components/checkbox-group',
    summary: 'A set of related checkboxes managed as one multi-select value.',
    title: 'Checkbox Group',
    visualFixture: 'checkbox-group.html.txt',
  },
  {
    component: 'collapsible',
    demoFunction: 'CollapsibleDemo',
    path: '/components/collapsible',
    summary:
      'A native <details>/<summary> reveal that expands or collapses one region and works without JavaScript - the simplest progressive-enhancement show/hide.',
    title: 'Collapsible',
    visualFixture: 'collapsible.html.txt',
  },
  {
    component: 'combobox',
    demoFunction: 'ComboboxDemo',
    path: '/components/combobox',
    summary: 'An input paired with a filterable listbox for selecting one option from many.',
    title: 'Combobox',
    visualFixture: 'combobox.html.txt',
  },
  {
    component: 'command',
    demoFunction: 'CommandDemo',
    path: '/components/command',
    summary: 'A searchable command palette that filters actions and runs the selected one.',
    title: 'Command',
    visualFixture: 'command.html.txt',
  },
  {
    component: 'context-menu',
    demoFunction: 'ContextMenuDemo',
    path: '/components/context-menu',
    summary: 'A right-click menu of actions anchored to the element it targets.',
    title: 'Context Menu',
    visualFixture: 'context-menu.html.txt',
  },
  {
    component: 'dialog',
    demoFunction: 'DialogDemo',
    path: '/components/dialog',
    summary:
      'A focus-trapped modal overlay for content or forms, dismissible by escape or backdrop.',
    title: 'Dialog',
    visualFixture: 'dialog.html.txt',
  },
  {
    component: 'disclosure',
    demoFunction: 'DisclosureDemo',
    path: '/components/disclosure',
    summary:
      'A scripted reveal pairing a <button aria-expanded> trigger with a controlled region, for show/hide cases that need full control over a non-native trigger and content.',
    title: 'Disclosure',
    visualFixture: 'disclosure.html.txt',
  },
  {
    component: 'drawer',
    demoFunction: 'DrawerDemo',
    path: '/components/drawer',
    summary: 'A panel that slides in from a screen edge, often for navigation or filters.',
    title: 'Drawer',
    visualFixture: 'drawer.html.txt',
  },
  {
    component: 'dropdown-menu',
    demoFunction: 'DropdownMenuDemo',
    path: '/components/dropdown-menu',
    summary: 'A button-triggered menu of actions with keyboard navigation.',
    title: 'Dropdown Menu',
    visualFixture: 'dropdown-menu.html.txt',
  },
  {
    component: 'field',
    demoFunction: 'FieldDemo',
    path: '/components/field',
    summary:
      'A labeled form-control wrapper that wires up label, description, and error messaging.',
    title: 'Field',
    visualFixture: 'field.html.txt',
  },
  {
    component: 'hover-card',
    demoFunction: 'HoverCardDemo',
    path: '/components/hover-card',
    summary: 'A rich preview card that opens on hover or focus of its trigger.',
    title: 'Hover Card',
    visualFixture: 'hover-card.html.txt',
  },
  {
    component: 'kbd',
    demoFunction: 'KbdDemo',
    path: '/components/kbd',
    summary: 'Inline styling for a keyboard key or shortcut chord.',
    title: 'Kbd',
    visualFixture: 'kbd.html.txt',
  },
  {
    component: 'menubar',
    demoFunction: 'MenubarDemo',
    path: '/components/menubar',
    summary: "A horizontal bar of menus, like a desktop application's menu strip.",
    title: 'Menubar',
    visualFixture: 'menubar.html.txt',
  },
  {
    component: 'meter',
    demoFunction: 'MeterDemo',
    path: '/components/meter',
    summary: 'A static gauge showing a scalar value within a known range.',
    title: 'Meter',
    visualFixture: 'meter.html.txt',
  },
  {
    component: 'navigation-menu',
    demoFunction: 'NavigationMenuDemo',
    path: '/components/navigation-menu',
    summary: 'A site navigation bar with expandable submenus.',
    title: 'Navigation Menu',
    visualFixture: 'navigation-menu.html.txt',
  },
  {
    component: 'number-field',
    demoFunction: 'NumberFieldDemo',
    path: '/components/number-field',
    summary: 'A numeric input with stepper buttons and min/max/step constraints.',
    title: 'Number Field',
    visualFixture: 'number-field.html.txt',
  },
  {
    component: 'otp-field',
    demoFunction: 'OtpFieldDemo',
    path: '/components/otp-field',
    summary: 'A segmented input for entering a one-time passcode digit by digit.',
    title: 'OTP Field',
    visualFixture: 'otp-field.html.txt',
  },
  {
    component: 'popover',
    demoFunction: 'PopoverDemo',
    path: '/components/popover',
    summary: 'A non-modal floating panel anchored to a trigger.',
    title: 'Popover',
    visualFixture: 'popover.html.txt',
  },
  {
    component: 'progress',
    demoFunction: 'ProgressDemo',
    path: '/components/progress',
    summary: 'A bar that communicates the completion percentage of a task.',
    title: 'Progress',
    visualFixture: 'progress.html.txt',
  },
  {
    component: 'radio-group',
    demoFunction: 'RadioGroupDemo',
    path: '/components/radio-group',
    summary: 'A set of mutually exclusive options where exactly one is selected.',
    title: 'Radio Group',
    visualFixture: 'radio-group.html.txt',
  },
  {
    component: 'scroll-area',
    demoFunction: 'ScrollAreaDemo',
    path: '/components/scroll-area',
    summary: 'A custom-styled scroll container with consistent cross-browser scrollbars.',
    title: 'Scroll Area',
    visualFixture: 'scroll-area.html.txt',
  },
  {
    component: 'select',
    demoFunction: 'SelectDemo',
    path: '/components/select',
    summary: 'A trigger that opens a listbox to choose one option, with a native fallback.',
    title: 'Select',
    visualFixture: 'select.html.txt',
  },
  {
    component: 'separator',
    demoFunction: 'SeparatorDemo',
    path: '/components/separator',
    summary: 'A semantic or decorative divider between groups of content.',
    title: 'Separator',
    visualFixture: 'separator.html.txt',
  },
  {
    component: 'sheet',
    demoFunction: 'SheetDemo',
    path: '/components/sheet',
    summary: 'A large panel that slides over the page from an edge for secondary tasks.',
    title: 'Sheet',
    visualFixture: 'sheet.html.txt',
  },
  {
    component: 'skeleton',
    demoFunction: 'SkeletonDemo',
    path: '/components/skeleton',
    summary: 'A placeholder shape that stands in for content while it loads.',
    title: 'Skeleton',
    visualFixture: 'skeleton.html.txt',
  },
  {
    component: 'slider',
    demoFunction: 'SliderDemo',
    path: '/components/slider',
    summary: 'A draggable thumb that selects a value or range along a track.',
    title: 'Slider',
    visualFixture: 'slider.html.txt',
  },
  {
    component: 'switch',
    demoFunction: 'SwitchDemo',
    path: '/components/switch',
    summary: 'A toggle styled as an on/off switch for an immediate boolean setting.',
    title: 'Switch',
    visualFixture: 'switch.html.txt',
  },
  {
    component: 'table',
    demoFunction: 'TableDemo',
    path: '/components/table',
    summary: 'A semantic data table with header, body, and styled rows.',
    title: 'Table',
    visualFixture: 'table.html.txt',
  },
  {
    component: 'tabs',
    demoFunction: 'TabsDemo',
    path: '/components/tabs',
    summary: 'A set of tabbed panels where one panel is visible at a time.',
    title: 'Tabs',
    visualFixture: 'tabs.html.txt',
  },
  {
    component: 'toast',
    demoFunction: 'ToastDemo',
    path: '/components/toast',
    summary: 'A transient, non-blocking notification that auto-dismisses.',
    title: 'Toast',
    visualFixture: 'toast.html.txt',
  },
  {
    component: 'toggle',
    demoFunction: 'ToggleDemo',
    path: '/components/toggle',
    summary: 'A two-state button that stays pressed or unpressed.',
    title: 'Toggle',
    visualFixture: 'toggle.html.txt',
  },
  {
    component: 'toggle-group',
    demoFunction: 'ToggleGroupDemo',
    path: '/components/toggle-group',
    summary: 'A set of toggle buttons acting as a single- or multi-select control.',
    title: 'Toggle Group',
    visualFixture: 'toggle-group.html.txt',
  },
  {
    component: 'toolbar',
    demoFunction: 'ToolbarDemo',
    path: '/components/toolbar',
    summary: 'A container grouping buttons and controls with roving-tabindex navigation.',
    title: 'Toolbar',
    visualFixture: 'toolbar.html.txt',
  },
  {
    component: 'tooltip',
    demoFunction: 'TooltipDemo',
    path: '/components/tooltip',
    summary: 'A small label that appears on hover or focus to describe its trigger.',
    title: 'Tooltip',
    visualFixture: 'tooltip.html.txt',
  },
] as const);

export type GalleryComponent = (typeof galleryComponentEntries)[number]['component'];
export type GalleryComponentPath = (typeof galleryComponentEntries)[number]['path'];
