export const kovoHeadlessUiPrefix = 'kovo-' as const;

export {
  checkedState,
  cn,
  computeFloatingPosition,
  createChangeDetail,
  dataDisabled,
  dataOrientation,
  dataState,
  defaultTypeaheadTimeoutMs,
  defineVariants,
  dispatchCancelableChange,
  findTypeaheadMatch,
  kovoUiDocumentTokenCss,
  kovoUiTokenSheet,
  kovoUiTokenSheetCss,
  mergeDataAttributes,
  moveCollectionIndex,
  navigationIntentFromKey,
  nextTypeaheadState,
  openState,
  oppositePlacement,
  pressedState,
  safeUrl,
  variantClassNames,
} from './lib/index.js';
export type {
  ClassArray,
  ClassDictionary,
  ClassValue,
  CollectionOrientation,
  FloatingOffset,
  FloatingOverflow,
  FloatingPlacement,
  FloatingPlacementAlign,
  FloatingPlacementSide,
  FloatingPosition,
  FloatingPositionOptions,
  FloatingRect,
  FloatingSize,
  KovoUiDocumentTokenProperty,
  KovoUiTokenCategory,
  KovoUiTokenDefinition,
  KovoUiTokenMode,
  KovoUiTokenName,
  KovoUiTokenProperty,
  MoveOptions,
  NavigationIntent,
  NavigationItem,
  NavigationKeyOptions,
  PrimitiveChangeDetail,
  PrimitiveChangeDetailInput,
  PrimitiveDataAttributes,
  PrimitiveStateToken,
  TextDirection,
  TypeaheadItem,
  TypeaheadMatchOptions,
  TypeaheadState,
  VariantClass,
  VariantCompound,
  VariantDefinition,
  VariantFn,
  VariantGroups,
  VariantOptions,
  VariantSelection,
  VariantValues,
} from './lib/index.js';
