export const jisoHeadlessUiPrefix = 'jiso-' as const;

export {
  getPrimitivePlatformAudit,
  h1HeadlessUiPrimitives,
  h1PlatformAudit,
  primitivesRequiringLazyFallback,
  primitiveUsesNativeMechanism,
} from './platform-audit.js';
export type {
  HeadlessUiH1Primitive,
  LazyFallbackModule,
  NativePlatformMechanism,
  PlatformConcern,
  PlatformConcernAudit,
  PrimitivePlatformAudit,
} from './platform-audit.js';

export {
  checkedState,
  cn,
  createChangeDetail,
  dataDisabled,
  dataOrientation,
  dataState,
  defaultTypeaheadTimeoutMs,
  defineVariants,
  dispatchCancelableChange,
  findTypeaheadMatch,
  computeFloatingPosition,
  jisoUiTailwindThemeCss,
  jisoUiTokenSheet,
  jisoUiTokenSheetCss,
  mergeDataAttributes,
  moveCollectionIndex,
  navigationIntentFromKey,
  nextTypeaheadState,
  oppositePlacement,
  openState,
  pressedState,
  variantClassNames,
} from './lib/index.js';
export type {
  ClassArray,
  ClassDictionary,
  ClassValue,
  CollectionOrientation,
  FloatingOffset,
  FloatingOverflow,
  FloatingPlacement,
  FloatingPlacementAlign,
  FloatingPlacementSide,
  FloatingPosition,
  FloatingPositionOptions,
  FloatingRect,
  FloatingSize,
  JisoUiTailwindThemeProperty,
  JisoUiTokenCategory,
  JisoUiTokenDefinition,
  JisoUiTokenMode,
  JisoUiTokenName,
  JisoUiTokenProperty,
  MoveOptions,
  NavigationIntent,
  NavigationItem,
  NavigationKeyOptions,
  PrimitiveChangeDetail,
  PrimitiveChangeDetailInput,
  PrimitiveDataAttributes,
  PrimitiveStateToken,
  TextDirection,
  TypeaheadItem,
  TypeaheadMatchOptions,
  TypeaheadState,
  VariantClass,
  VariantCompound,
  VariantDefinition,
  VariantFn,
  VariantGroups,
  VariantOptions,
  VariantSelection,
  VariantValues,
} from './lib/index.js';

export {
  collapsibleContentAttributes,
  collapsibleRootAttributes,
  collapsibleTriggerAttributes,
  collapsibleTriggerClick,
  disclosureContentAttributes,
  disclosureRootAttributes,
  disclosureTriggerAttributes,
  disclosureTriggerClick,
  meterRootAttributes,
  meterValueState,
  progressRootAttributes,
  progressValueState,
  separatorRootAttributes,
  setCollapsibleOpen,
  setDisclosureOpen,
  toggleCollapsible,
  toggleDisclosure,
} from './primitives/index.js';
export type {
  CollapsibleAttributeOptions,
  CollapsibleChangeDetail,
  CollapsibleChangeOptions,
  CollapsibleChangeReason,
  CollapsibleChangeResult,
  CollapsiblePrimitiveAttributes,
  CollapsibleState,
  CollapsibleTriggerEvent,
  DisclosureAttributeOptions,
  DisclosureChangeDetail,
  DisclosureChangeOptions,
  DisclosureChangeReason,
  DisclosureChangeResult,
  DisclosurePrimitiveAttributes,
  DisclosureState,
  DisclosureTriggerEvent,
  MeterAttributeOptions,
  MeterComputedState,
  MeterDataState,
  MeterPrimitiveAttributes,
  ProgressAttributeOptions,
  ProgressComputedState,
  ProgressDataState,
  ProgressPrimitiveAttributes,
  SeparatorAttributeOptions,
  SeparatorOrientation,
  SeparatorPrimitiveAttributes,
} from './primitives/index.js';
