import type { PatchOp, PatchProgram, SymbolicValue } from '@kovojs/core/internal/derivation';

// SPEC.md §10.4/§10.5 Phase 3 — lower a Stage-3 PatchProgram into a committed,
// reviewable, overridable transform module (`generated/optimistic/*.ts`). This is
// the ONLY place that turns the IR into TypeScript source; the deriver core stays
// source-free. Output is `(current, $input) => Value` transforms inside an
// `OptimisticFor`-shaped plan, with a DO-NOT-EDIT header (SPEC.md §10.4 example).

/** @internal One derived (non-overridden) transform to emit into the generated plan. */
export interface DerivedTransformEntry {
  program: PatchProgram;
  query: string;
}

/** @internal */
export interface SerializeDerivedOptimisticOptions {
  /** Exported binding name, e.g. `cartAddDerivedOptimistic`. */
  constName: string;
  /** True when every invalidated query of the mutation is derived (no overrides) ⇒ emit `satisfies`. */
  complete: boolean;
  entries: readonly DerivedTransformEntry[];
  /** Query names that are covered by waiting for the server fragment. */
  awaitFragments?: readonly string[];
  /** Type-only import of the mutation form, e.g. `{ name: 'addToCartForm', path: '../../app.js' }`. */
  formImport: { name: string; path: string };
  /** Optional named FIFO serialization queue (mirrors the hand-written plan). */
  queue?: string;
  /** Query names covered by a hand-written transform / `'await-fragment'` (suppressed here). */
  overrides?: readonly string[];
}

const DO_NOT_EDIT = [
  '// DO NOT EDIT — generated by @kovojs/drizzle derived optimism (SPEC.md §10.5).',
  '// Override a transform by declaring it in the mutation module; deleting the',
  '// override lets derivation take this pair back over, pair by pair (SPEC.md §10.4).',
].join('\n');

/**
 * @internal
 *
 * Serialize derived transforms for one mutation into a `generated/optimistic/*.ts`
 * module. Override precedence: callers pass only the non-overridden `entries`, so a
 * hand-written transform present ⇒ its derived entry is suppressed; deleting the
 * hand-written entry ⇒ the next generation re-emits the derived entry.
 */
export function serializeDerivedOptimistic(options: SerializeDerivedOptimisticOptions): string {
  const sorted = [...options.entries].sort((left, right) => left.query.localeCompare(right.query));
  const awaitFragments = [...(options.awaitFragments ?? [])].sort();
  const usesTempId = sorted.some((entry) => programUses(entry.program, 'tempId'));
  const usesNow = sorted.some((entry) => programUses(entry.program, 'now'));

  const runtimeValueImports = [usesNow ? 'now' : null, usesTempId ? 'tempId' : null].filter(
    (name): name is string => name !== null,
  );
  const runtimeImport =
    runtimeValueImports.length > 0
      ? `import { ${runtimeValueImports.join(', ')}, type OptimisticFor } from '@kovojs/browser';`
      : `import type { OptimisticFor } from '@kovojs/browser';`;

  const transforms = [
    ...sorted.map((entry) => `${propertyKey(entry.query)}: ${lowerTransform(entry.program)},`),
    ...awaitFragments.map((query) => `${propertyKey(query)}: 'await-fragment',`),
  ]
    .map((line) => indent(line, 4))
    .join('\n');

  const planBody = [
    options.queue === undefined ? null : indent(`queue: '${options.queue}',`, 2),
    indent('transforms: {', 2),
    transforms,
    indent('},', 2),
  ]
    .filter((line): line is string => line !== null)
    .join('\n');

  const satisfies = options.complete
    ? ` satisfies OptimisticFor<typeof ${options.formImport.name}>`
    : '';
  const overrideNote =
    options.overrides && options.overrides.length > 0
      ? `\n// Overridden in the mutation module (derivation suppressed): ${[...options.overrides]
          .sort()
          .join(', ')}.`
      : '';

  return `${DO_NOT_EDIT}
${runtimeImport}

import type { ${options.formImport.name} } from '${options.formImport.path}';${overrideNote}

export const ${options.constName} = {
${planBody}
}${satisfies};
`;
}

/**
 * @internal
 *
 * Lower one PatchProgram to a pure `(current, $input) => Value` transform arrow —
 * the exact source committed into the generated plan, and the unit under the
 * codegen↔interpreter parity test (it must agree with `applyPatchProgram`).
 */
export function lowerTransform(program: PatchProgram): string {
  // Indent relative to the arrow's own start (body +2, close +0); the caller
  // re-indents the whole arrow to its nesting depth, keeping braces aligned.
  const statements = program.ops.flatMap((op) => lowerOp(op));
  const body = ['const next = structuredClone(current);', ...statements, 'return next;']
    .map((line) => indent(line, 2))
    .join('\n');
  // Some sound transforms never read the mutation input (e.g. a +1 count inc or a
  // provably no-op program). `$input` is only ever lowered as `$input.<path>`, so
  // name the parameter `_$input` when the body never references it — keeping the
  // committed codegen lint-clean (no-unused-vars).
  const inputParam = body.includes('$input.') ? '$input' : '_$input';
  return `(current, ${inputParam}) => {\n${body}\n}`;
}

function lowerOp(op: PatchOp): string[] {
  switch (op.op) {
    case 'inc':
      return [`next.${op.path} = (next.${op.path} ?? 0) + ${lowerValue(op.by)};`];
    case 'set-field':
      return [`next.${op.path} = ${lowerValue(op.value)};`];
    case 'recount':
      return [`next.${op.path} = next.${op.from}.length;`];
    case 'resum':
      return [
        `next.${op.path} = next.${op.from}.reduce((sum, row) => sum + (row.${op.column} ?? 0), 0);`,
      ];
    case 'remove-row':
      return [
        `{`,
        `  const index = next.${op.path}.findIndex((entry) => ${matchExpression(op.match)});`,
        `  if (index >= 0) next.${op.path}.splice(index, 1);`,
        `}`,
      ];
    case 'update-row':
      return [
        `{`,
        `  const target = next.${op.path}.find((entry) => ${matchExpression(op.match)});`,
        `  if (target) {`,
        ...Object.entries(op.sets).map(
          ([column, value]) => `    target.${column} = ${lowerValue(value, 'target')};`,
        ),
        `  }`,
        `}`,
      ];
    case 'push-row':
      return lowerPush(op);
  }
}

function lowerPush(op: Extract<PatchOp, { op: 'push-row' }>): string[] {
  const rowLiteral = `{ ${Object.entries(op.row)
    .map(([column, value]) => `${propertyKey(column)}: ${lowerValue(value)}`)
    .join(', ')} }`;
  if (op.position === 'start') return [`next.${op.path}.unshift(${rowLiteral});`];
  if (op.position === 'end') return [`next.${op.path}.push(${rowLiteral});`];
  const comparison =
    op.position.direction === 'asc'
      ? `entry.${op.position.column} > row.${op.position.column}`
      : `entry.${op.position.column} < row.${op.position.column}`;
  return [
    `{`,
    `  const row = ${rowLiteral};`,
    `  const index = next.${op.path}.findIndex((entry) => ${comparison});`,
    `  if (index < 0) next.${op.path}.push(row);`,
    `  else next.${op.path}.splice(index, 0, row);`,
    `}`,
  ];
}

function matchExpression(match: readonly { column: string; value: SymbolicValue }[]): string {
  return match.map((entry) => `entry.${entry.column} === ${lowerValue(entry.value)}`).join(' && ');
}

function lowerValue(value: SymbolicValue, rowVar?: string): string {
  switch (value.kind) {
    case 'arith':
      return `(${lowerValue(value.left, rowVar)} ${value.op} ${lowerValue(value.right, rowVar)})`;
    case 'col':
      return rowVar ? `${rowVar}.${value.column}` : `current.${value.column}`;
    case 'const':
      return JSON.stringify(value.value);
    case 'opaque':
      // Should never reach codegen — the deriver replaces opaque INSERT cols with
      // placeholders and punts opaque SET/match before a program is emitted.
      throw new Error(`derive-codegen: opaque value (${value.expr}) is not lowerable`);
    case 'param':
      return `$input.${value.path}`;
    case 'placeholder':
      return value.placeholder === 'now' ? 'now()' : 'tempId()';
  }
}

function programUses(program: PatchProgram, placeholder: 'now' | 'tempId'): boolean {
  return program.ops.some((op) => op.op === 'push-row' && rowUses(op.row, placeholder));
}

function rowUses(
  row: Readonly<Record<string, SymbolicValue>>,
  placeholder: 'now' | 'tempId',
): boolean {
  return Object.values(row).some(
    (value) => value.kind === 'placeholder' && value.placeholder === placeholder,
  );
}

function propertyKey(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return text
    .split('\n')
    .map((line) => (line.length > 0 ? pad + line : line))
    .join('\n');
}
