import type { PatchOp, PatchProgram, SymbolicValue } from '@kovojs/core/internal/derivation';

// SPEC.md §10.4/§10.5 Phase 3 — lower a Stage-3 PatchProgram into a committed,
// reviewable, overridable transform module (`generated/optimistic/*.ts`). This is
// the ONLY place that turns the IR into TypeScript source; the deriver core stays
// source-free. Output is draft-style `(draft, $input) => void` transforms inside an
// `OptimisticFor`-shaped plan, with a DO-NOT-EDIT header (SPEC.md §10.4 example).

/** @internal One derived (non-overridden) transform to emit into the generated plan. */
export interface DerivedTransformEntry {
  program: PatchProgram;
  query: string;
}

/** @internal */
export interface SerializeDerivedOptimisticOptions {
  /** Exported binding name, e.g. `cartAddDerivedOptimistic`. */
  constName: string;
  /** True when every invalidated query of the mutation is derived (no overrides) ⇒ emit `satisfies`. */
  complete: boolean;
  entries: readonly DerivedTransformEntry[];
  /** Query names that are covered by waiting for the server fragment. */
  awaitFragments?: readonly string[];
  /** Type-only import of the mutation form, e.g. `{ name: 'addToCartForm', path: '../../app.js' }`. */
  formImport: { name: string; path: string };
  /** Optional named FIFO serialization queue (mirrors the hand-written plan). */
  queue?: string;
  /** Query names covered by a hand-written transform / `'await-fragment'` (suppressed here). */
  overrides?: readonly string[];
}

const DO_NOT_EDIT = [
  '// DO NOT EDIT — generated by @kovojs/drizzle derived optimism (SPEC.md §10.5).',
  '// Override a transform by declaring it in the mutation module; deleting the',
  '// override lets derivation take this pair back over, pair by pair (SPEC.md §10.4).',
].join('\n');

/**
 * @internal
 *
 * Serialize derived transforms for one mutation into a `generated/optimistic/*.ts`
 * module. Override precedence: callers pass only the non-overridden `entries`, so a
 * hand-written transform present ⇒ its derived entry is suppressed; deleting the
 * hand-written entry ⇒ the next generation re-emits the derived entry.
 */
export function serializeDerivedOptimistic(options: SerializeDerivedOptimisticOptions): string {
  const sorted = [...options.entries].sort((left, right) => left.query.localeCompare(right.query));
  const awaitFragments = [...(options.awaitFragments ?? [])].sort();
  const usesTempId = sorted.some((entry) => programUses(entry.program, 'tempId'));
  const usesNow = sorted.some((entry) => programUses(entry.program, 'now'));

  const runtimeValueImports = [usesNow ? 'now' : null, usesTempId ? 'tempId' : null].filter(
    (name): name is string => name !== null,
  );
  const runtimeImport =
    runtimeValueImports.length > 0
      ? `import { ${runtimeValueImports.join(', ')}, type OptimisticFor } from '@kovojs/browser';`
      : `import type { OptimisticFor } from '@kovojs/browser';`;

  const transforms = [
    ...sorted.map((entry) => `${propertyKey(entry.query)}: ${lowerTransform(entry.program)},`),
    ...awaitFragments.map((query) => `${propertyKey(query)}: 'await-fragment',`),
  ]
    .map((line) => indent(line, 4))
    .join('\n');

  const planBody = [
    options.queue === undefined ? null : indent(`queue: '${options.queue}',`, 2),
    indent('transforms: {', 2),
    transforms,
    indent('},', 2),
  ]
    .filter((line): line is string => line !== null)
    .join('\n');

  const satisfies = options.complete
    ? ` satisfies OptimisticFor<typeof ${options.formImport.name}>`
    : '';
  const overrideNote =
    options.overrides && options.overrides.length > 0
      ? `\n// Overridden in the mutation module (derivation suppressed): ${[...options.overrides]
          .sort()
          .join(', ')}.`
      : '';

  return `${DO_NOT_EDIT}
${runtimeImport}

import type { ${options.formImport.name} } from '${options.formImport.path}';${overrideNote}

export const ${options.constName} = {
${planBody}
}${satisfies};
`;
}

// SPEC.md §6.1 / §10.6 / §11.1 — emit the app's `@kovojs/core` registry augmentation as a
// generated module-augmentation artifact instead of a hand-authored `declare module` block.
// The compiler emits the same interfaces from compiled components (compiler/src/emit/registry.ts);
// this serializer covers the Drizzle data-plane path: it folds the (analyzer-derived) mutation
// touch graph against the query read set into `InvalidationSets`, and maps each query to its
// loader result type in `QueryRegistry`, so `OptimisticFor`/the inline `mutation({optimistic})`
// exhaustiveness check (SPEC.md §10.6, server/mutation/definition.ts `MutationOptimisticMap`)
// bites WITHOUT the app hand-listing the mutation→query union (which silently drifts from the real
// invalidation graph, capability-gaps §3). Pair with `OptimisticDerivationSets` once derived
// optimism is wired (SPEC.md §10.5); until then it stays empty so every invalidated query is a
// REQUIRED optimistic entry.

/** @internal One `QueryRegistry` entry: a query key and the TypeScript type its loader produces. */
export interface CoreRegistryQueryEntry {
  /** The query registry key (must match the query's `query('<name>', …)` key). */
  name: string;
  /** The result type expression, e.g. `QueryResult<typeof import('../queries.js').questionList>`. */
  type: string;
}

/** @internal Options for {@link serializeCoreRegistryModule}. */
export interface SerializeCoreRegistryModuleOptions {
  /** `QueryRegistry` entries (query key → loader result type expression). */
  queries: readonly CoreRegistryQueryEntry[];
  /** `InvalidationSets` entries: mutation key → invalidated query keys. */
  invalidations: Readonly<Record<string, readonly string[]>>;
  /** `OptimisticDerivationSets` entries: mutation key → derived (optional) query keys (SPEC.md §10.5). */
  derivations?: Readonly<Record<string, readonly string[]>>;
  /** Top-level imports the type expressions reference (also make the file a module for augmentation). */
  headerImports?: readonly string[];
}

const REGISTRY_DO_NOT_EDIT = [
  '// DO NOT EDIT — generated @kovojs/core registry augmentation (SPEC.md §6.1/§10.6/§11.1).',
  '// Produced from the Drizzle touch graph + query read set so the mutation→query',
  '// InvalidationSets union cannot drift from the real graph (capability-gaps §3).',
  '// QueryRegistry result types come from each query loader, the single source of truth.',
].join('\n');

/**
 * @internal
 *
 * Serialize a `declare module '@kovojs/core'` augmentation (`QueryRegistry`, `InvalidationSets`,
 * and `OptimisticDerivationSets`) into a generated `.d.ts`/`.ts` module the app's `tsc` program
 * includes (SPEC.md §6.1/§10.6/§11.1). The file is a module (top-level imports), so the
 * `declare module` block is a declaration-merging augmentation, not an ambient redefinition.
 */
export function serializeCoreRegistryModule(options: SerializeCoreRegistryModuleOptions): string {
  const queryLines = [...options.queries]
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((entry) => indent(`${propertyKey(entry.name)}: ${entry.type};`, 4))
    .join('\n');
  const invalidationLines = registryUnionLines(options.invalidations);
  const derivationLines = registryUnionLines(options.derivations ?? {});
  const header = (options.headerImports ?? []).join('\n');

  return `${REGISTRY_DO_NOT_EDIT}
${header}

declare module '@kovojs/core' {
  interface QueryRegistry {
${queryLines}
  }

  interface InvalidationSets {
${invalidationLines}
  }

  interface OptimisticDerivationSets {
${derivationLines}
  }
}
`;
}

function registryUnionLines(map: Readonly<Record<string, readonly string[]>>): string {
  return Object.entries(map)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, queries]) => {
      const union =
        [...new Set(queries)]
          .sort()
          .map((query) => `'${query}'`)
          .join(' | ') || 'never';
      return indent(`${propertyKey(key)}: ${union};`, 4);
    })
    .join('\n');
}

/**
 * @internal
 *
 * Lower one PatchProgram to a pure draft-style `(draft, $input) => void` transform arrow —
 * the exact source committed into the generated plan, and the unit under the
 * codegen↔interpreter parity test (it must agree with `applyPatchProgram`).
 */
export function lowerTransform(program: PatchProgram): string {
  assertNoPrivateScopeLeak(program);
  // Indent relative to the arrow's own start (body +2, close +0); the caller
  // re-indents the whole arrow to its nesting depth, keeping braces aligned.
  const statements = program.ops.flatMap((op) => lowerOp(op));
  // C5 (SPEC.md §10.5:1172) — node-postgres serializes numeric/decimal/bigint columns
  // as STRINGS, so raw `+`/`<`/`>` would string-concatenate or lexically mis-order them
  // and codegen would disagree with the interpreter. Prepend the shared `n(...)` numeric
  // coercion helper — byte-for-byte the interpreter's `asNumber` — whenever the body
  // performs arithmetic/numeric comparison, so the committed transform is self-contained
  // and identical in meaning to `applyPatchProgram`.
  const lines = programNeedsNumericCoercion(program) ? [NUMERIC_HELPER, ...statements] : statements;
  const body = lines.map((line) => indent(line, 2)).join('\n');
  // Some sound transforms never read the mutation input (e.g. a +1 count inc or a
  // provably no-op program). `$input` is only ever lowered as `$input.<path>`, so
  // name the parameter `_$input` when the body never references it — keeping the
  // committed codegen lint-clean (no-unused-vars).
  const inputParam = body.includes('$input.') ? '$input' : '_$input';
  return `(draft, ${inputParam}) => {\n${body}\n}`;
}

// Numeric coercion helper emitted into a transform body — IDENTICAL semantics to the
// interpreter's `asNumber` in `@kovojs/core` derivation (SPEC.md §10.5:1172 commuting
// diagram): a `number` passes through; anything else (PG string numeric/decimal/bigint,
// null/undefined) is `Number(v ?? 0)`.
const NUMERIC_HELPER = 'const n = (v) => (typeof v === "number" ? v : Number(v ?? 0));';

function lowerOp(op: PatchOp): string[] {
  switch (op.op) {
    case 'inc':
      // C5/C6 — coerce both the held SUM/COUNT base and the increment numerically,
      // exactly as the interpreter's `asNumber`, so a string-decimal base does not
      // string-concatenate and codegen ≡ interpreter (SPEC.md §10.5:1172).
      return [`draft.${op.path} = n(draft.${op.path}) + n(${lowerValue(op.by)});`];
    case 'set-field':
      return [`draft.${op.path} = ${lowerValue(op.value)};`];
    case 'recount':
      return [`draft.${op.path} = draft.${op.from}.length;`];
    case 'resum':
      // C5 — coerce each contribution numerically (the interpreter reduces with
      // `asNumber(row[col] ?? 0)`), so string-decimal columns sum rather than concat.
      return [
        `draft.${op.path} = draft.${op.from}.reduce((sum, row) => sum + n(row.${op.column}), 0);`,
      ];
    case 'remove-row':
      return [
        `{`,
        `  const index = draft.${op.path}.findIndex((entry) => ${matchExpression(op.match)});`,
        `  if (index >= 0) draft.${op.path}.splice(index, 1);`,
        `}`,
      ];
    case 'update-row':
      return [
        `{`,
        `  const target = draft.${op.path}.find((entry) => ${matchExpression(op.match)});`,
        `  if (target) {`,
        ...Object.entries(op.sets).map(
          ([column, value]) => `    target.${column} = ${lowerValue(value, 'target')};`,
        ),
        `  }`,
        `}`,
      ];
    case 'push-row':
      return lowerPush(op);
  }
}

function lowerPush(op: Extract<PatchOp, { op: 'push-row' }>): string[] {
  const rowLiteral = `{ ${Object.entries(op.row)
    .map(([column, value]) => `${propertyKey(column)}: ${lowerValue(value)}`)
    .join(', ')} }`;
  if (op.position === 'start') return [`draft.${op.path}.unshift(${rowLiteral});`];
  if (op.position === 'end') return [`draft.${op.path}.push(${rowLiteral});`];
  // M11 (SPEC.md §10.5) — a sorted `push-row` position reaches codegen only for a PROVABLY
  // numeric orderBy column: the deriver (`insertPosition`) punts a non-numeric (text)
  // orderBy to `await-fragment` (NaN compare ⇒ append ⇒ divergence from the server's
  // lexical ORDER BY). So the numeric `n(...)` compare below is sound and matches the
  // interpreter's `insertRow`.
  // C5 — coerce both sides of the orderBy compare numerically (the interpreter
  // compares `asNumber(...)` on both), so a string-numeric orderBy column does not
  // sort lexically ("10" before "9"); codegen ≡ interpreter (SPEC.md §10.5:1172).
  const comparison =
    op.position.direction === 'asc'
      ? `n(entry.${op.position.column}) > n(row.${op.position.column})`
      : `n(entry.${op.position.column}) < n(row.${op.position.column})`;
  return [
    `{`,
    `  const row = ${rowLiteral};`,
    `  const index = draft.${op.path}.findIndex((entry) => ${comparison});`,
    `  if (index < 0) draft.${op.path}.push(row);`,
    `  else draft.${op.path}.splice(index, 0, row);`,
    `}`,
  ];
}

function assertNoPrivateScopeLeak(program: PatchProgram): void {
  for (const op of program.ops) {
    switch (op.op) {
      case 'inc':
        assertNoPrivateScopeValue(op.by);
        break;
      case 'set-field':
        assertNoPrivateScopeValue(op.value);
        break;
      case 'remove-row':
        assertNoPrivateScopeMatch(op.match);
        break;
      case 'update-row':
        assertNoPrivateScopeMatch(op.match);
        for (const value of Object.values(op.sets)) assertNoPrivateScopeValue(value);
        break;
      case 'push-row':
        for (const value of Object.values(op.row)) assertNoPrivateScopeValue(value);
        break;
      case 'recount':
      case 'resum':
        break;
    }
  }
}

function assertNoPrivateScopeMatch(
  match: readonly { column: string; value: SymbolicValue }[],
): void {
  for (const entry of match) assertNoPrivateScopeValue(entry.value);
}

function assertNoPrivateScopeValue(value: SymbolicValue): void {
  switch (value.kind) {
    case 'arith':
      assertNoPrivateScopeValue(value.left);
      assertNoPrivateScopeValue(value.right);
      return;
    case 'guard':
    case 'session':
    case 'tenant':
      throw new Error(
        `derive-codegen: private scope value leaked into optimistic codegen (${value.kind}:${value.path})`,
      );
    case 'col':
    case 'const':
    case 'opaque':
    case 'param':
    case 'placeholder':
      return;
  }
}

function matchExpression(match: readonly { column: string; value: SymbolicValue }[]): string {
  return match.map((entry) => `entry.${entry.column} === ${lowerValue(entry.value)}`).join(' && ');
}

function lowerValue(value: SymbolicValue, rowVar?: string): string {
  switch (value.kind) {
    case 'arith':
      // C5 — the interpreter coerces both operands (`asNumber`) before `applyArith`;
      // mirror it so string-decimal cols/params don't string-concat or NaN-coerce
      // differently across lowerings (SPEC.md §10.5:1172).
      return `(n(${lowerValue(value.left, rowVar)}) ${value.op} n(${lowerValue(value.right, rowVar)}))`;
    case 'col':
      return rowVar ? `${rowVar}.${value.column}` : `draft.${value.column}`;
    case 'const':
      return JSON.stringify(value.value);
    case 'opaque':
      // Should never reach codegen — the deriver replaces opaque INSERT cols with
      // placeholders and punts opaque SET/match before a program is emitted.
      throw new Error(`derive-codegen: opaque value (${value.expr}) is not lowerable`);
    case 'param':
      return `$input.${value.path}`;
    case 'placeholder':
      return value.placeholder === 'now' ? 'now()' : 'tempId()';
    case 'guard':
      throw new Error(`derive-codegen: guard value (${value.path}) is not lowerable`);
    case 'session':
      // SPEC.md §10.2 / advanced-analyzer: private session scope is proof-only.
      // The deriver must eliminate it from browser-visible row matches before codegen.
      throw new Error(`derive-codegen: session value (${value.path}) is not lowerable`);
    case 'tenant':
      throw new Error(`derive-codegen: tenant value (${value.path}) is not lowerable`);
  }
}

function programUses(program: PatchProgram, placeholder: 'now' | 'tempId'): boolean {
  return program.ops.some((op) => op.op === 'push-row' && rowUses(op.row, placeholder));
}

/**
 * Whether a lowered transform body performs arithmetic / numeric comparison and so
 * must prepend the `n(...)` coercion helper (C5, SPEC.md §10.5:1172). True for `inc`,
 * `resum`, an orderBy-sorted `push-row`, and any `arith` value anywhere in the program.
 */
function programNeedsNumericCoercion(program: PatchProgram): boolean {
  return program.ops.some((op) => {
    switch (op.op) {
      case 'inc':
        return true;
      case 'resum':
        return true;
      case 'push-row':
        return (
          (typeof op.position === 'object' && op.position !== null) ||
          Object.values(op.row).some(valueUsesArith)
        );
      case 'set-field':
        return valueUsesArith(op.value);
      case 'update-row':
        return (
          op.match.some((entry) => valueUsesArith(entry.value)) ||
          Object.values(op.sets).some(valueUsesArith)
        );
      case 'remove-row':
        return op.match.some((entry) => valueUsesArith(entry.value));
      case 'recount':
        return false;
    }
  });
}

/** An `arith` value lowers its operands wrapped in `n(...)`, so it needs the helper. */
function valueUsesArith(value: SymbolicValue): boolean {
  return value.kind === 'arith';
}

function rowUses(
  row: Readonly<Record<string, SymbolicValue>>,
  placeholder: 'now' | 'tempId',
): boolean {
  return Object.values(row).some(
    (value) => value.kind === 'placeholder' && value.placeholder === placeholder,
  );
}

function propertyKey(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return text
    .split('\n')
    .map((line) => (line.length > 0 ? pad + line : line))
    .join('\n');
}
