import { tokens } from '@kovojs/style';
import * as style from '@kovojs/style';

export const commerceStyles = style.create(
  {
    appRoot: {
      backgroundColor: tokens.sys.color.surface,
      color: tokens.sys.color.onSurface,
      minHeight: '100dvh',
    },
    cartCount: {
      alignItems: 'center',
      backgroundColor: tokens.sys.color.primary,
      borderRadius: tokens.sys.shape.cornerFull,
      color: tokens.sys.color.onPrimary,
      display: 'inline-flex',
      fontSize: 12,
      fontVariantNumeric: 'tabular-nums',
      fontWeight: 600,
      height: 20,
      justifyContent: 'center',
      minWidth: 20,
      paddingInline: 6,
    },
    cartBadge: {
      alignItems: 'center',
      backgroundColor: tokens.sys.color.surfaceContainerLowest,
      borderColor: tokens.sys.color.outlineVariant,
      borderRadius: tokens.sys.shape.cornerMedium,
      borderStyle: 'solid',
      borderWidth: 1,
      color: tokens.sys.color.onSurface,
      display: 'inline-flex',
      fontSize: 14,
      fontWeight: 500,
      gap: 8,
      paddingBlock: 8,
      paddingInline: 12,
    },
    cartShell: {
      marginInline: 'auto',
      maxWidth: 896,
    },
    errorText: {
      color: tokens.sys.color.error,
      fontSize: 14,
    },
    field: {
      backgroundColor: tokens.sys.color.surfaceContainerLowest,
      borderColor: tokens.sys.color.outline,
      borderRadius: tokens.sys.shape.cornerMedium,
      borderStyle: 'solid',
      borderWidth: 1,
      boxSizing: 'border-box',
      color: tokens.sys.color.onSurface,
      paddingBlock: 6,
      paddingInline: 10,
    },
    formInline: {
      display: 'inline',
    },
    formLabel: {
      color: tokens.sys.color.onSurfaceVariant,
      display: 'grid',
      fontSize: 12,
      fontWeight: 500,
      gap: 4,
    },
    loginForm: {
      backgroundColor: tokens.sys.color.surfaceContainerLowest,
      borderColor: tokens.sys.color.outlineVariant,
      borderRadius: tokens.sys.shape.cornerMedium,
      borderStyle: 'solid',
      borderWidth: 1,
      display: 'grid',
      gap: 16,
      padding: 24,
    },
    loginMain: {
      marginInline: 'auto',
      maxWidth: 448,
      padding: 24,
    },
    mutedText: {
      color: tokens.sys.color.onSurfaceVariant,
      fontSize: 12,
    },
    orderItem: {
      alignItems: 'center',
      backgroundColor: tokens.sys.color.surfaceContainerLowest,
      borderColor: tokens.sys.color.outlineVariant,
      borderRadius: tokens.sys.shape.cornerMedium,
      borderStyle: 'solid',
      borderWidth: 1,
      display: 'flex',
      justifyContent: 'space-between',
      paddingBlock: 12,
      paddingInline: 16,
    },
    panelError: {
      backgroundColor: tokens.sys.color.errorContainer,
      borderColor: tokens.sys.color.error,
      borderRadius: tokens.sys.shape.cornerMedium,
      borderStyle: 'solid',
      borderWidth: 1,
      color: tokens.sys.color.onErrorContainer,
      fontSize: 14,
      padding: 16,
    },
    productEmoji: {
      backgroundColor: tokens.sys.color.surfaceContainer,
      borderRadius: tokens.sys.shape.cornerMedium,
      display: 'grid',
      fontSize: 24,
      height: 48,
      placeItems: 'center',
      width: 48,
    },
    productForm: {
      alignItems: 'end',
      display: 'flex',
      flexWrap: 'wrap',
      gap: 8,
    },
    productLink: {
      color: tokens.sys.color.primary,
      fontSize: 14,
      fontWeight: 500,
      textDecoration: 'none',
    },
    primaryButton: {
      backgroundColor: tokens.sys.color.primary,
      borderColor: tokens.sys.color.primary,
      borderRadius: tokens.sys.shape.cornerMedium,
      borderStyle: 'solid',
      borderWidth: 1,
      color: tokens.sys.color.onPrimary,
      fontSize: 14,
      fontWeight: 500,
      paddingBlock: 8,
      paddingInline: 16,
    },
    row: {
      alignItems: 'center',
      display: 'flex',
      gap: 16,
    },
    rowBetween: {
      alignItems: 'center',
      display: 'flex',
      justifyContent: 'space-between',
    },
    stack: {
      display: 'grid',
      gap: 16,
    },
    stackSm: {
      display: 'grid',
      gap: 4,
    },
    tabularStrong: {
      fontVariantNumeric: 'tabular-nums',
      fontWeight: 600,
    },
    title: {
      color: tokens.sys.color.onSurface,
      fontWeight: 600,
      letterSpacing: 0,
      margin: 0,
    },
  },
  { namespace: 'commerce', source: 'examples/commerce/src/styles.ts' },
);

export const commerceStyleCss = style.emitAtomicCss(
  Object.values(commerceStyles).flatMap((entry) => entry.__rules ?? []),
);
