export { createApp, createRequestHandler } from './app.js';
export { isKovoApp } from './app-guards.js';
export { guardAccess, publicAccess, verifiedAccess } from './access.js';
export type {
  AccessDecision,
  GuardAccessStep,
  GuardChainAccess,
  PublicAccess,
  VerifiedMachineAccess,
} from './access.js';
// SPEC.md §9.5: apps inject a custom versioned client-module registry through
// `createApp({ clientModules })`. Real example/site consumers (examples/gallery,
// crm, stackoverflow, reference; site/src/client/modules.ts) construct one with
// `createMemoryVersionedClientModuleRegistry`, so the constructor and its option
// surface stay public at the root barrel (also available on the internal subpath).
export { createMemoryVersionedClientModuleRegistry } from './client-modules.js';
export { toNodeHandler } from './node.js';
export { exportStaticApp } from './static-export.js';
export { StaticExportError } from './static-export-diagnostics.js';
// SPEC.md §9.5: app authors wire the app shell into their Vite dev server from
// vite.config.ts (the create-kovo starter template does exactly this). These stay
// public at the root barrel and also remain on `@kovojs/server/internal/app-shell-vite`.
/**
 * @experimental
 */
export { createKovoAppShellViteDevIntegration, kovoAppShellViteDevPlugin } from './vite-dev.js';
export type {
  AppDiagnostic,
  AppDocumentOptions,
  AppErrorShellOptions,
  AppMutationResponseContext,
  AppMutationResponseOptions,
  AppMutationResponseResolver,
  AppRateLimitOptions,
  AppRequestLimitOptions,
  AppRequestRateLimitOptions,
  AppRouteRenderContext,
  CreateAppOptions,
  ErrorShellRenderer,
  KovoApp,
  RequestHandler,
  ResolvedAppRateLimitOptions,
  ResolvedAppRequestLimitOptions,
  ResolvedAppRequestRateLimitOptions,
} from './app-types.js';
// Option/registry types named by `createApp({ clientModules })` and by app
// consumers that hold a registry reference (recursive publicness,
// rules/api-surface.md). They also remain on `@kovojs/server/internal/client-modules`.
export type {
  MemoryVersionedClientModuleRegistryOptions,
  VersionedClientModuleInput,
  VersionedClientModuleRegistry,
} from './client-modules.js';
export type { NodeHandlerOptions, NodeRequestHandler } from './node.js';
export type {
  StaticExportCompileDiagnostic,
  StaticExportDiagnostic,
  StaticExportDiagnosticSeverity,
} from './static-export-diagnostics.js';
export type {
  StaticExportNonExportablePolicy,
  StaticExportOptions,
  StaticExportResult,
} from './static-export-types.js';
// SPEC.md §9.5 / rules/api-surface.md: the dev integration/plugin companion types
// (KovoAppShellViteCompilerModuleDiagnosticReport, KovoAppShellViteDevIntegration,
// KovoAppShellViteDevPlugin, KovoAppShellViteDevPluginOptions) are not re-exported
// from the root barrel; they remain available on
// `@kovojs/server/internal/app-shell-vite`.
// rules/api-surface.md "No `export *` on a public barrel": public package barrels
// must use explicit named re-exports so the surface is reviewed on change. These
// blocks enumerate exactly the names re-exported by ./api/data.js,
// ./api/rendering.js, and ./api/routing.js.
export {
  createMemoryMutationReplayStore,
  csrfField,
  csrfToken,
  domain,
  errorBoundary,
  mutation,
  mutationFormAttributes,
  query,
  s,
  SchemaValidationError,
  stream,
  tag,
  write,
} from './api/data.js';
export type {
  ChangeRecord,
  CsrfAnonymousCookieOptions,
  CsrfOptions,
  CsrfValidationOptions,
  ArraySchema,
  AsyncSchema,
  Domain,
  FileLike,
  FileSchema,
  FileSchemaOptions,
  InferSchema,
  InvalidateOptions,
  MutationContext,
  MutationDefinition,
  MutationFail,
  MutationFormAttributes,
  MutationFormDefinition,
  MutationReplayReservation,
  MutationReplayStore,
  MutationResult,
  MutationStreamChunk,
  MutationStreamContext,
  MutationStreamDoneChunk,
  MutationStreamFragmentChunk,
  MutationStreamFragmentHtml,
  MutationStreamQueryChunk,
  MutationStreamSource,
  MutationStreamTextChunk,
  MutationSuccess,
  MutationTextCoalescingPolicy,
  NumberSchema,
  QueryDeclarationDefinition,
  QueryDefinition,
  JsonSerializable,
  QueryLoadContext,
  QueryResult,
  Schema,
  Secret,
  StringSchema,
  StoredFileSchema,
  StoredFileSchemaOptions,
  StoredFileUpload,
  Tag,
  ValidationFailurePayload,
  ValidationIssue,
  WriteDefinition,
} from './api/data.js';
export {
  cspSha256,
  Defer,
  i18n,
  meta,
  metaFromQuery,
  renderContentSecurityPolicy,
  stylesheet,
  t,
} from './api/rendering.js';
export type {
  ContentSecurityPolicyOptions,
  CspInlineMetadata,
  DeferProps,
  DocumentParts,
  DocumentTemplate,
  DocumentTemplateContext,
  I18nCatalog,
  PageHintOptions,
  RouteMeta,
  RouteMetaFactory,
  RouteMetaSource,
  RoutePrefetch,
  RegionPriority,
  ServerRenderable,
  StylesheetAsset,
  StylesheetDeclarationOptions,
  StylesheetTheme,
} from './api/rendering.js';
export {
  endpoint,
  guards,
  href,
  layout,
  Link,
  notFound,
  redirect,
  respond,
  route,
  session,
  webhook,
} from './api/routing.js';
export type {
  AuthenticatedRequest,
  CookieOptions,
  DeferredFragmentChunk,
  DeferredPriority,
  DeferredQueryChunk,
  DeferredStreamChunk,
  DiagnosticCode,
  Endpoint,
  EndpointAuthDeclaration,
  EndpointCsrfExemption,
  EndpointDeclaration,
  EndpointDefinition,
  EndpointHandler,
  EndpointMountDefinition,
  EndpointMethod,
  EndpointMount,
  EndpointReason,
  EndpointRequest,
  EndpointCachePosture,
  EndpointResponseBody,
  EndpointResponsePosture,
  ForbiddenContext,
  ForbiddenDenial,
  ForbiddenRenderer,
  Guard,
  GuardDenial,
  GuardFailure,
  GuardResult,
  JsonValue,
  LayoutDeclaration,
  LayoutDefinition,
  LayoutFactory,
  LayoutQueryResults,
  LayoutRenderResult,
  LayoutRenderSlots,
  LinkDescriptor,
  MutationResponseHeaders,
  MutationResponseHeaderValue,
  NotFound,
  RateLimitedDenial,
  RateLimitOptions,
  Redirect,
  ResponseHeaders,
  ResponseHeaderValue,
  Route,
  RouteBoundaries,
  RouteBoundaryContext,
  RouteBoundaryRenderer,
  RouteDeclaration,
  RouteDefinition,
  RouteFileOptions,
  RoutePageResponse,
  RoutePageResult,
  RouteRequest,
  RouteRequestInput,
  RouteResponseBody,
  RouteResponseOutcome,
  RouteStreamOptions,
  ServerErrorDiagnosticContext,
  ServerErrorHandler,
  ServerResponseBase,
  SessionDefinition,
  SessionProvider,
  SessionProviderResult,
  SessionRequestLike,
  SessionUserLike,
  UnauthenticatedContext,
  UnauthenticatedDenial,
  UnauthenticatedHandler,
  WebhookChangeOptions,
  WebhookDeclaration,
  WebhookDefinition,
  WebhookFail,
  WebhookHandlerContext,
  WebhookTransactionContext,
} from './api/routing.js';
