/** @internal Finite component enum shared by the semantic CLI and vendored catalog loader. */
export const KOVO_ADD_COMPONENT_NAMES = [
  'accordion',
  'alert',
  'alert-dialog',
  'autocomplete',
  'avatar',
  'badge',
  'breadcrumb',
  'button',
  'card',
  'checkbox',
  'checkbox-group',
  'collapsible',
  'combobox',
  'command',
  'context-menu',
  'dialog',
  'disclosure',
  'drawer',
  'dropdown-menu',
  'field',
  'hover-card',
  'kbd',
  'menubar',
  'meter',
  'navigation-menu',
  'number-field',
  'otp-field',
  'popover',
  'progress',
  'radio-group',
  'scroll-area',
  'select',
  'separator',
  'sheet',
  'skeleton',
  'slider',
  'switch',
  'table',
  'tabs',
  'toast',
  'toggle',
  'toggle-group',
  'toolbar',
  'tooltip',
] as const;

/** @internal One literal component accepted by `kovo add`. */
export type AddComponentName = (typeof KOVO_ADD_COMPONENT_NAMES)[number];
