// Generated from spec/11-diagnostics.md by scripts/generate-diagnostic-registry.mjs.
// Do not edit by hand. SPEC §2 and §11 own the source registry and enforcement classes.
import {
  createDiagnosticConstructor,
  createRegisteredDiagnosticDefinition,
  freezeGeneratedDiagnosticMap,
  type DiagnosticConstructorRegistry,
  type RegisteredDiagnosticRegistry,
} from '../diagnostics.js';

/** @internal Normative diagnostics registry paired with SPEC §2 enforcement classes. */
export const diagnosticRegistry = freezeGeneratedDiagnosticMap({
  KV201: createRegisteredDiagnosticDefinition('KV201', 'compile-error'),
  KV210: createRegisteredDiagnosticDefinition('KV210', 'audited-escape'),
  KV211: createRegisteredDiagnosticDefinition('KV211', 'audited-escape'),
  KV212: createRegisteredDiagnosticDefinition('KV212', 'audited-escape'),
  KV220: createRegisteredDiagnosticDefinition('KV220', 'compile-error'),
  KV221: createRegisteredDiagnosticDefinition('KV221', 'compile-error'),
  KV222: createRegisteredDiagnosticDefinition('KV222', 'compile-error'),
  KV223: createRegisteredDiagnosticDefinition('KV223', 'audited-escape'),
  KV224: createRegisteredDiagnosticDefinition('KV224', 'compile-error'),
  KV225: createRegisteredDiagnosticDefinition('KV225', 'compile-error'),
  KV226: createRegisteredDiagnosticDefinition('KV226', 'compile-error'),
  KV227: createRegisteredDiagnosticDefinition('KV227', 'compile-error'),
  KV228: createRegisteredDiagnosticDefinition('KV228', 'compile-error'),
  KV229: createRegisteredDiagnosticDefinition('KV229', 'compile-error'),
  KV230: createRegisteredDiagnosticDefinition('KV230', 'compile-error'),
  KV231: createRegisteredDiagnosticDefinition('KV231', 'compile-error'),
  KV232: createRegisteredDiagnosticDefinition('KV232', 'audited-escape'),
  KV233: createRegisteredDiagnosticDefinition('KV233', 'compile-error'),
  KV234: createRegisteredDiagnosticDefinition('KV234', 'compile-error'),
  KV235: createRegisteredDiagnosticDefinition('KV235', 'compile-error'),
  KV236: createRegisteredDiagnosticDefinition('KV236', 'compile-error'),
  KV237: createRegisteredDiagnosticDefinition('KV237', 'compile-error'),
  KV238: createRegisteredDiagnosticDefinition('KV238', 'compile-error'),
  KV239: createRegisteredDiagnosticDefinition('KV239', 'compile-error'),
  KV240: createRegisteredDiagnosticDefinition('KV240', 'compile-error'),
  KV241: createRegisteredDiagnosticDefinition('KV241', 'audited-escape'),
  KV242: createRegisteredDiagnosticDefinition('KV242', 'compile-error'),
  KV243: createRegisteredDiagnosticDefinition('KV243', 'compile-error'),
  KV244: createRegisteredDiagnosticDefinition('KV244', 'audited-escape'),
  KV245: createRegisteredDiagnosticDefinition('KV245', 'compile-error'),
  KV246: createRegisteredDiagnosticDefinition('KV246', 'audited-escape'),
  KV247: createRegisteredDiagnosticDefinition('KV247', 'audited-escape'),
  KV301: createRegisteredDiagnosticDefinition('KV301', 'audited-escape'),
  KV302: createRegisteredDiagnosticDefinition('KV302', 'compile-error'),
  KV303: createRegisteredDiagnosticDefinition('KV303', 'compile-error'),
  KV304: createRegisteredDiagnosticDefinition('KV304', 'compile-error'),
  KV310: createRegisteredDiagnosticDefinition('KV310', 'audited-escape'),
  KV311: createRegisteredDiagnosticDefinition('KV311', 'audited-escape'),
  KV312: createRegisteredDiagnosticDefinition('KV312', 'compile-error'),
  KV313: createRegisteredDiagnosticDefinition('KV313', 'fail-closed-runtime'),
  KV314: createRegisteredDiagnosticDefinition('KV314', 'compile-error'),
  KV315: createRegisteredDiagnosticDefinition('KV315', 'audited-escape'),
  KV316: createRegisteredDiagnosticDefinition('KV316', 'compile-error'),
  KV317: createRegisteredDiagnosticDefinition('KV317', 'compile-error'),
  KV318: createRegisteredDiagnosticDefinition('KV318', 'audited-escape'),
  KV320: createRegisteredDiagnosticDefinition('KV320', 'audited-escape'),
  KV330: createRegisteredDiagnosticDefinition('KV330', 'compile-error'),
  KV402: createRegisteredDiagnosticDefinition('KV402', 'fail-closed-runtime'),
  KV403: createRegisteredDiagnosticDefinition('KV403', 'audited-escape'),
  KV404: createRegisteredDiagnosticDefinition('KV404', 'fail-closed-runtime'),
  KV405: createRegisteredDiagnosticDefinition('KV405', 'fail-closed-runtime'),
  KV406: createRegisteredDiagnosticDefinition('KV406', 'compile-error'),
  KV407: createRegisteredDiagnosticDefinition('KV407', 'fail-closed-runtime'),
  KV408: createRegisteredDiagnosticDefinition('KV408', 'fail-closed-runtime'),
  KV409: createRegisteredDiagnosticDefinition('KV409', 'audited-escape'),
  KV410: createRegisteredDiagnosticDefinition('KV410', 'compile-error'),
  KV411: createRegisteredDiagnosticDefinition('KV411', 'compile-error'),
  KV412: createRegisteredDiagnosticDefinition('KV412', 'compile-error'),
  KV413: createRegisteredDiagnosticDefinition('KV413', 'compile-error'),
  KV414: createRegisteredDiagnosticDefinition('KV414', 'compile-error'),
  KV415: createRegisteredDiagnosticDefinition('KV415', 'fail-closed-runtime'),
  KV416: createRegisteredDiagnosticDefinition('KV416', 'compile-error'),
  KV417: createRegisteredDiagnosticDefinition('KV417', 'compile-error'),
  KV418: createRegisteredDiagnosticDefinition('KV418', 'compile-error'),
  KV419: createRegisteredDiagnosticDefinition('KV419', 'compile-error'),
  KV420: createRegisteredDiagnosticDefinition('KV420', 'compile-error'),
  KV421: createRegisteredDiagnosticDefinition('KV421', 'compile-error'),
  KV422: createRegisteredDiagnosticDefinition('KV422', 'compile-error'),
  KV423: createRegisteredDiagnosticDefinition('KV423', 'compile-error'),
  KV424: createRegisteredDiagnosticDefinition('KV424', 'compile-error'),
  KV425: createRegisteredDiagnosticDefinition('KV425', 'compile-error'),
  KV426: createRegisteredDiagnosticDefinition('KV426', 'compile-error'),
  KV428: createRegisteredDiagnosticDefinition('KV428', 'fail-closed-runtime'),
  KV429: createRegisteredDiagnosticDefinition('KV429', 'compile-error'),
  KV430: createRegisteredDiagnosticDefinition('KV430', 'audited-escape'),
  KV431: createRegisteredDiagnosticDefinition('KV431', 'audited-escape'),
  KV432: createRegisteredDiagnosticDefinition('KV432', 'fail-closed-runtime'),
  KV433: createRegisteredDiagnosticDefinition('KV433', 'compile-error'),
  KV434: createRegisteredDiagnosticDefinition('KV434', 'compile-error'),
  KV435: createRegisteredDiagnosticDefinition('KV435', 'compile-error'),
  KV436: createRegisteredDiagnosticDefinition('KV436', 'compile-error'),
  KV437: createRegisteredDiagnosticDefinition('KV437', 'compile-error'),
  KV438: createRegisteredDiagnosticDefinition('KV438', 'compile-error'),
  KV439: createRegisteredDiagnosticDefinition('KV439', 'compile-error'),
  KV445: createRegisteredDiagnosticDefinition('KV445', 'compile-error'),
  KV446: createRegisteredDiagnosticDefinition('KV446', 'compile-error'),
  KV447: createRegisteredDiagnosticDefinition('KV447', 'audited-escape'),
  KV448: createRegisteredDiagnosticDefinition('KV448', 'compile-error'),
  KV449: createRegisteredDiagnosticDefinition('KV449', 'compile-error'),
  KV450: createRegisteredDiagnosticDefinition('KV450', 'fail-closed-runtime'),
  KV451: createRegisteredDiagnosticDefinition('KV451', 'compile-error'),
  KV452: createRegisteredDiagnosticDefinition('KV452', 'compile-error'),
} satisfies RegisteredDiagnosticRegistry);

/** @internal Typed, registry-derived constructor for every normative KV diagnostic. */
export const diagnosticConstructors = freezeGeneratedDiagnosticMap({
  KV201: createDiagnosticConstructor('KV201'),
  KV210: createDiagnosticConstructor('KV210'),
  KV211: createDiagnosticConstructor('KV211'),
  KV212: createDiagnosticConstructor('KV212'),
  KV220: createDiagnosticConstructor('KV220'),
  KV221: createDiagnosticConstructor('KV221'),
  KV222: createDiagnosticConstructor('KV222'),
  KV223: createDiagnosticConstructor('KV223'),
  KV224: createDiagnosticConstructor('KV224'),
  KV225: createDiagnosticConstructor('KV225'),
  KV226: createDiagnosticConstructor('KV226'),
  KV227: createDiagnosticConstructor('KV227'),
  KV228: createDiagnosticConstructor('KV228'),
  KV229: createDiagnosticConstructor('KV229'),
  KV230: createDiagnosticConstructor('KV230'),
  KV231: createDiagnosticConstructor('KV231'),
  KV232: createDiagnosticConstructor('KV232'),
  KV233: createDiagnosticConstructor('KV233'),
  KV234: createDiagnosticConstructor('KV234'),
  KV235: createDiagnosticConstructor('KV235'),
  KV236: createDiagnosticConstructor('KV236'),
  KV237: createDiagnosticConstructor('KV237'),
  KV238: createDiagnosticConstructor('KV238'),
  KV239: createDiagnosticConstructor('KV239'),
  KV240: createDiagnosticConstructor('KV240'),
  KV241: createDiagnosticConstructor('KV241'),
  KV242: createDiagnosticConstructor('KV242'),
  KV243: createDiagnosticConstructor('KV243'),
  KV244: createDiagnosticConstructor('KV244'),
  KV245: createDiagnosticConstructor('KV245'),
  KV246: createDiagnosticConstructor('KV246'),
  KV247: createDiagnosticConstructor('KV247'),
  KV301: createDiagnosticConstructor('KV301'),
  KV302: createDiagnosticConstructor('KV302'),
  KV303: createDiagnosticConstructor('KV303'),
  KV304: createDiagnosticConstructor('KV304'),
  KV310: createDiagnosticConstructor('KV310'),
  KV311: createDiagnosticConstructor('KV311'),
  KV312: createDiagnosticConstructor('KV312'),
  KV313: createDiagnosticConstructor('KV313'),
  KV314: createDiagnosticConstructor('KV314'),
  KV315: createDiagnosticConstructor('KV315'),
  KV316: createDiagnosticConstructor('KV316'),
  KV317: createDiagnosticConstructor('KV317'),
  KV318: createDiagnosticConstructor('KV318'),
  KV320: createDiagnosticConstructor('KV320'),
  KV330: createDiagnosticConstructor('KV330'),
  KV402: createDiagnosticConstructor('KV402'),
  KV403: createDiagnosticConstructor('KV403'),
  KV404: createDiagnosticConstructor('KV404'),
  KV405: createDiagnosticConstructor('KV405'),
  KV406: createDiagnosticConstructor('KV406'),
  KV407: createDiagnosticConstructor('KV407'),
  KV408: createDiagnosticConstructor('KV408'),
  KV409: createDiagnosticConstructor('KV409'),
  KV410: createDiagnosticConstructor('KV410'),
  KV411: createDiagnosticConstructor('KV411'),
  KV412: createDiagnosticConstructor('KV412'),
  KV413: createDiagnosticConstructor('KV413'),
  KV414: createDiagnosticConstructor('KV414'),
  KV415: createDiagnosticConstructor('KV415'),
  KV416: createDiagnosticConstructor('KV416'),
  KV417: createDiagnosticConstructor('KV417'),
  KV418: createDiagnosticConstructor('KV418'),
  KV419: createDiagnosticConstructor('KV419'),
  KV420: createDiagnosticConstructor('KV420'),
  KV421: createDiagnosticConstructor('KV421'),
  KV422: createDiagnosticConstructor('KV422'),
  KV423: createDiagnosticConstructor('KV423'),
  KV424: createDiagnosticConstructor('KV424'),
  KV425: createDiagnosticConstructor('KV425'),
  KV426: createDiagnosticConstructor('KV426'),
  KV428: createDiagnosticConstructor('KV428'),
  KV429: createDiagnosticConstructor('KV429'),
  KV430: createDiagnosticConstructor('KV430'),
  KV431: createDiagnosticConstructor('KV431'),
  KV432: createDiagnosticConstructor('KV432'),
  KV433: createDiagnosticConstructor('KV433'),
  KV434: createDiagnosticConstructor('KV434'),
  KV435: createDiagnosticConstructor('KV435'),
  KV436: createDiagnosticConstructor('KV436'),
  KV437: createDiagnosticConstructor('KV437'),
  KV438: createDiagnosticConstructor('KV438'),
  KV439: createDiagnosticConstructor('KV439'),
  KV445: createDiagnosticConstructor('KV445'),
  KV446: createDiagnosticConstructor('KV446'),
  KV447: createDiagnosticConstructor('KV447'),
  KV448: createDiagnosticConstructor('KV448'),
  KV449: createDiagnosticConstructor('KV449'),
  KV450: createDiagnosticConstructor('KV450'),
  KV451: createDiagnosticConstructor('KV451'),
  KV452: createDiagnosticConstructor('KV452'),
} satisfies DiagnosticConstructorRegistry);
